export type ExerciseCategory = 'greeting' | 'places' | 'daily-activities' | 'numbers' | 'food-and-drink' | 'days-and-months' | 'period-of-time' | 'family' | 'occupations' | 'fruits' | 'feeling-and-adjective' | 'color' | 'parts-of-body' | 'transportation';

export const EXERCISE_CATEGORIES: { id: ExerciseCategory; label: string }[] = [
    { id: 'greeting', label: 'Greeting' },
    { id: 'places', label: 'Places' },
    { id: 'daily-activities', label: 'Daily Activities' },
    { id: 'numbers', label: 'Numbers' },
    { id: 'food-and-drink', label: 'Food and Drink' },
    { id: 'days-and-months', label: 'Days and Months' },
    { id: 'period-of-time', label: 'Period of Time' },
    { id: 'family', label: 'Family' },
    { id: 'occupations', label: 'Occupations' },
    { id: 'fruits', label: 'Fruits' },
    { id: 'feeling-and-adjective', label: 'Feeling and Adjective' },
    { id: 'color', label: 'Color' },
    { id: 'parts-of-body', label: 'Parts of Body' },
    { id: 'transportation', label: 'Transportation' },
];

export interface Exercise {
    prompt: string;
    thai: string;
    latinised: string;
    category: ExerciseCategory;
    audio?: string;
}

export const EXERCISES: Exercise[] = [
    // ── Greeting ────────────────────────────────────────────────────
    { prompt: 'is it hot?', thai: 'คุณร้อนไหมครับ?', latinised: 'kun rɔ́ɔn mái kráp?', category: 'greeting', audio: '2023-05-16-14-08-38intro-session1_69.mp3' },
    { prompt: 'are you having fun?', thai: 'เขาสนุกไหมคะ?', latinised: 'káo sa nùk mái ká(?)', category: 'greeting', audio: '2023-05-16-14-35-33intro-session1_70.mp3' },
    { prompt: 'are you tired?', thai: 'คุณเหนื่อยไหมครับ?', latinised: 'kun nuài mái kráp?', category: 'greeting', audio: '2023-05-16-14-42-09intro-session1_72.mp3' },
    { prompt: 'are you hungry?', thai: 'เขาหิวไหมคะ?', latinised: 'káo hǐw mái ká(?)', category: 'greeting', audio: '2023-05-16-14-43-43intro-session1_73.mp3' },
    { prompt: 'im very hot?', thai: 'ผมร้อนมากๆ', latinised: 'pǒm rɔ́ɔn mâak mâak', category: 'greeting', audio: '2023-05-16-14-45-26intro-session1_74.mp3' },
    { prompt: 'im very fun?', thai: 'ผมสนุกมากๆ', latinised: 'pǒm sa nùk mâak mâak', category: 'greeting', audio: '2023-05-16-14-57-05intro-session1_75.mp3' },
    { prompt: 'he/she a little tired', thai: 'เขาเหนื่อยนิดหน่อย', latinised: 'káo nuài nít nɔ̀ɔi', category: 'greeting', audio: '2023-05-16-14-59-06intro-session1_76.mp3' },
    { prompt: 'he/she a little hungry', thai: 'ดิฉันหิวนิดหน่อย', latinised: 'dichán hǐw nít nɔ̀ɔi', category: 'greeting', audio: '2023-05-16-15-03-27intro-session1_77.mp3' },
    { prompt: 'what country do you come from?', thai: 'คุณมาจากประเทศอะไรคะ?', latinised: 'kun maa jaàk bp̀ra teêt arai ká(?)', category: 'greeting', audio: '2023-05-16-15-14-54intro-session1_84.mp3' },
    { prompt: 'what city do you come from?', thai: 'คุณมาจากเมืองอะไรคะ?', latinised: 'kun maa jaàk muang arai ká(?)', category: 'greeting', audio: '2023-05-16-15-18-01intro-session1_85.mp3' },
    { prompt: 'what province do you come from?', thai: 'เขามาจากจังหวัดอะไรครับ?', latinised: 'káo maa jaàk jang wàt arai kráp?', category: 'greeting', audio: '2023-05-16-15-19-23intro-session1_86.mp3' },
    { prompt: 'what state do you come from?', thai: 'เขามาจากรัฐอะไรครับ?', latinised: 'káo maa jaàk rát arai kráp?', category: 'greeting', audio: '2023-05-16-15-20-40intro-session1_87.mp3' },
    { prompt: 'aom form chiang mai', thai: 'อ้อมมาจากจังหวัดเชียงใหม่ค่ะ', latinised: 'aom maa jaàk jang wàt chiang mai ká', category: 'greeting', audio: '2023-05-16-15-29-44intro-session1_91.mp3' },
    { prompt: 'what is it?', thai: 'นี่อะไร', latinised: 'nîi aria', category: 'greeting', audio: '2023-05-16-16-25-00intro-session1_129.mp3' },
    { prompt: 'what did you say?', thai: 'อะไรนะ?', latinised: 'arai ná?', category: 'greeting', audio: '2023-05-16-16-28-19intro-session1_130.mp3' },
    // ── Places ──────────────────────────────────────────────────────
    { prompt: 'where is rest room?', thai: 'ห้องน้ำอยู่ที่ไหน?', latinised: 'hɔ̂ɔng naám yùu t̂ii ňai', category: 'places', audio: '2023-05-16-11-10-03session2_5.mp3' },
    { prompt: 'where is your house?', thai: 'บ้านของคุณอยู่ที่ไหน?', latinised: 'bâan kɔ̌ɔng kun yùu t̂ii ňai (?)', category: 'places', audio: '2023-05-16-11-33-17session2_24.mp3' },
    { prompt: 'where is your mother?', thai: 'แม่ของเขาอยู่ที่ไหน?', latinised: 'mâe kɔ̌ɔng káo yùu t̂ii ňai (?)', category: 'places', audio: '2023-05-16-11-36-32session2_25.mp3' },
    { prompt: 'my mother is in america', thai: 'แม่ของผมอยู่ที่อเมริกา', latinised: 'mâe kɔ̌ɔng pǒm yùu t̂ii à mee ri gaa', category: 'places', audio: '2023-05-16-11-40-38session2_26.mp3' },
    { prompt: 'where do you like to travel?', thai: 'คุณชอบไปเที่ยวที่ไหนคะ?', latinised: 'kun chɔ̂ɔp bpai tiâw t̂ii ňai (?)', category: 'places', audio: '2023-05-16-11-54-59session2_30.mp3' },
    { prompt: 'i like to travel', thai: 'ผมชอบไปเที่ยว', latinised: 'pǒm chɔ̂ɔp bpai tiâw', category: 'places', audio: '2023-05-16-11-59-49session2_31.mp3' },
    { prompt: 'where will you go?', thai: 'คุณไปไหน?', latinised: 'kun bpai ňai (?)', category: 'places', audio: '2023-05-16-14-38-43session2_65.mp3' },
    { prompt: 'where have you been?', thai: 'คุณไปไหนมา?', latinised: 'kun bpai ňai maa (?)', category: 'places', audio: '2023-05-16-14-39-18session2_66.mp3' },
    // ── Daily Activities ────────────────────────────────────────────
    { prompt: 'what did he buy', thai: 'เขาซื้ออะไร?', latinised: 'káo súu arai(?)', category: 'daily-activities', audio: '2023-05-16-16-06-30session3_24.mp3' },
    { prompt: 'he bought a house', thai: 'เขาซื้อบ้าน', latinised: 'káo súu bâan', category: 'daily-activities', audio: '2023-05-16-16-11-03session3_25.mp3' },
    { prompt: 'he bought a car', thai: 'เขาซื้อรถ', latinised: 'káo súu rót', category: 'daily-activities', audio: '2023-05-16-16-12-32session3_26.mp3' },
    { prompt: 'what do you want to eat', thai: 'คุณอยากกินอะไร', latinised: 'kun yàak gin arai', category: 'daily-activities', audio: '2023-05-16-16-41-01session3_32.mp3' },
    { prompt: 'what do you want to do', thai: 'คุณอยากทำอะไร?', latinised: 'kun yàak tam arai (?)', category: 'daily-activities', audio: '2023-05-18-09-24-58session3_33.mp3' },
    { prompt: 'what do you want to buy', thai: 'คุณอยากซื้ออะไร?', latinised: 'kun yàak súu arai (?)', category: 'daily-activities', audio: '2023-05-18-09-26-06session3_34.mp3' },
    { prompt: 'where do you want to go?', thai: 'คุณอยากไปที่ไหน?', latinised: 'kun yàak bpai t̂ii ňai(?)', category: 'daily-activities', audio: '2023-05-18-09-35-28session3_35.mp3' },
    { prompt: 'i want to travel', thai: 'ผมอยากไปเที่ยว', latinised: 'pǒm yàak bpai tiâw', category: 'daily-activities', audio: '2023-05-18-09-37-14session3_37.mp3' },
    { prompt: 'i want to eat', thai: 'ผมอยากกินข้าว', latinised: 'pǒm yàak gin kâaw', category: 'daily-activities', audio: '2023-05-18-09-38-14session3_38.mp3' },
    { prompt: 'i want to work', thai: 'ผมอยากทำงาน', latinised: 'pǒm yàak tam ngaan', category: 'daily-activities', audio: '2023-05-18-09-39-31session3_39.mp3' },
    { prompt: 'aom wants to see a movie', thai: 'อ้อมอยากดูหนัง', latinised: 'aom yàak duu nǎng', category: 'daily-activities', audio: '2023-05-18-09-41-36session3_40.mp3' },
    { prompt: 'aom wants to buy a car', thai: 'อ้อมอยากซื้อรถ', latinised: 'aom yàak súu rót', category: 'daily-activities', audio: '2023-05-18-09-43-11session3_41.mp3' },
    { prompt: 'he wants to play tennis', thai: 'เขาอยากเล่นเทนนิส', latinised: 'káo yàak lên ten nis', category: 'daily-activities', audio: '2023-05-18-09-47-37session3_42.mp3' },
    { prompt: 'can he cook japanese food?', thai: 'เขาทำอาหารญี่ปุ่นได้ไหมครับ?', latinised: 'káo tam aa hǎan ŷii bp̀un dâi mái (?)', category: 'daily-activities', audio: '2023-05-18-09-53-31session3_46.mp3' },
    { prompt: 'can you speak english?', thai: 'คุณพูดภาษาอังกฤษได้ไหม?', latinised: 'kun pûut paa sǎa ang gr̀it dâi mái (?)', category: 'daily-activities', audio: '2023-05-18-09-59-59session3_53.mp3' },
    { prompt: 'i can speak english', thai: 'ผมพูดภาษาอังกฤษได้', latinised: 'pǒm pûut paa sǎa ang gr̀it dâi', category: 'daily-activities', audio: '2023-05-18-10-02-22session3_54.mp3' },
    { prompt: 'he cooks japanese food', thai: 'เขาทำอาหารญี่ปุ่น', latinised: 'káo tam aa hǎan ŷii bp̀un', category: 'daily-activities', audio: '2023-05-18-10-13-01session3_55.mp3' },
    { prompt: 'what are you doing?', thai: 'คุณทำอะไรอยู่?', latinised: 'kun tam arai (yùu)?', category: 'daily-activities', audio: '2023-05-18-10-30-34session3_77.mp3' },
    { prompt: 'i don’t know', thai: 'ไม่รู้ค่ะ', latinised: 'mâi rúu', category: 'daily-activities', audio: '2023-05-18-10-33-22session3_78.mp3' },
    { prompt: 'do you know him / her ?', thai: 'คุณรู้จักเขาไหม?', latinised: 'kun rúu jàk káo mái ?', category: 'daily-activities', audio: '2023-05-18-10-33-56session3_79.mp3' },
    { prompt: 'i go for walk', thai: 'ผมไปเดินเล่น', latinised: 'pǒm bpai dəən lên', category: 'daily-activities', audio: '2023-05-18-10-34-37session3_80.mp3' },
    { prompt: 'i can speak english', thai: 'ผมพูดภาษาอังกฤษได้', latinised: 'pǒm pûut paa sǎa ang gr̀it dâi', category: 'daily-activities', audio: '2023-05-18-10-02-22session3_54.mp3' },
    { prompt: 'he cooks japanese food', thai: 'เขาทำอาหารญี่ปุ่น', latinised: 'káo tam aa hǎan ŷii bp̀un', category: 'daily-activities', audio: '2023-05-18-10-13-01session3_55.mp3' },
    { prompt: 'what are you doing?', thai: 'คุณทำอะไรอยู่?', latinised: 'kun tam arai (yùu)?', category: 'daily-activities', audio: '2023-05-18-10-30-34session3_77.mp3' },
    { prompt: 'i don’t know', thai: 'ไม่รู้ค่ะ', latinised: 'mâi rúu', category: 'daily-activities', audio: '2023-05-18-10-33-22session3_78.mp3' },
    { prompt: 'do you know him / her ?', thai: 'คุณรู้จักเขาไหม?', latinised: 'kun rúu jàk káo mái ?', category: 'daily-activities', audio: '2023-05-18-10-33-56session3_79.mp3' },
    { prompt: 'i go for walk', thai: 'ผมไปเดินเล่น', latinised: 'pǒm bpai dəən lên', category: 'daily-activities', audio: '2023-05-18-10-34-37session3_80.mp3' },
    { prompt: 'what did you eat?', thai: 'คุณกินอะไร?', latinised: 'kun gin arai(?)', category: 'daily-activities', audio: '2023-05-16-14-58-55session3_4.mp3' },
    { prompt: 'i eat rice', thai: 'ผมกินข้าว', latinised: 'pǒm gin kâaw', category: 'daily-activities', audio: '2023-05-16-15-09-03session3_5.mp3' },
    { prompt: 'i eat food', thai: 'ผมกินอาหาร', latinised: 'pǒm gin kâaw hǎan', category: 'daily-activities', audio: '2023-05-16-15-14-32session3_6.mp3' },
    { prompt: 'i drink water', thai: 'ผมกินน้ำ', latinised: 'pǒm gin naám', category: 'daily-activities', audio: '2023-05-16-15-17-23session3_7.mp3' },
    { prompt: 'what is he doing?', thai: 'เขาทำอะไร?', latinised: 'káo tam arai(?)', category: 'daily-activities', audio: '2023-05-16-15-31-52session3_13.mp3' },
    { prompt: 'i am doing some work', thai: 'ผมทำงาน', latinised: 'pǒm tam ngaan', category: 'daily-activities', audio: '2023-05-16-15-41-53session3_14.mp3' },
    { prompt: 'i am cooking', thai: 'ผมทำอาหาร', latinised: 'pǒm tam aa hǎan', category: 'daily-activities', audio: '2023-05-16-15-44-48session3_15.mp3' },
    { prompt: 'i do homework', thai: 'ผมทำการบ้าน', latinised: 'pǒm tam gaan bâan', category: 'daily-activities', audio: '2023-05-16-15-51-07session3_16.mp3' },
    // ── Numbers ─────────────────────────────────────────────────────
    { prompt: 'how much is this ?', thai: 'อันนี้กี่บาทคะ', latinised: 'an níi gìi bàat(?)', category: 'numbers', audio: '2023-05-24-15-03-35session4-1.mp3' },
    { prompt: 'how many dollars is this?', thai: 'อันนี้กี่ดอลลาร์คะ', latinised: 'an níi gìi dɔɔn lâa ?', category: 'numbers', audio: '2023-05-24-15-05-05session4-2.mp3' },
    { prompt: 'how many yen is this?', thai: 'อันนี้กี่เยนคะ', latinised: 'an níi gìi yeen ?', category: 'numbers', audio: '2023-05-24-15-06-24session4-3.mp3' },
    { prompt: 'this is 20 baht', thai: 'อันนี้ 20 บาท', latinised: 'an níi 20 bàat', category: 'numbers', audio: '2023-05-24-15-08-46session4-5.mp3' },
    { prompt: 'how much is that', thai: 'อันนั้นเท่าไหร่ครับ', latinised: 'an nàn tâo rài(?)', category: 'numbers', audio: '2023-05-24-15-16-05session4-7.mp3' },
    { prompt: 'don’t want to take (thing)', thai: 'ไม่เอา', latinised: 'm̂ai aow', category: 'numbers', audio: '2023-05-24-15-32-29session4-3.mp3' },
    { prompt: 'can you reduce it?', thai: 'ลดหน่อยได้ไหมคะ', latinised: 'lót nɔ̀ɔi dâi mái (?)', category: 'numbers', audio: '2023-05-24-15-55-11session4-8.mp3' },
    { prompt: 'can you get 500 baht?', thai: '500 บาทได้ไหมคะ', latinised: '500 dâi mái (?)', category: 'numbers', audio: '2023-05-24-15-56-57session4-9.mp3' },
    { prompt: 'how many baht is this one?', thai: 'อันนี้กี่บาทครับ?', latinised: 'an níi gìi bàat', category: 'numbers', audio: '2023-05-25-10-24-42session4-7.mp3' },
    { prompt: 'how much is this one?', thai: 'อันนี้เท่าไหร่คะ?', latinised: 'an níi tâo rài', category: 'numbers', audio: '2023-05-25-10-25-42session4-8.mp3' },
    { prompt: 'can you reduce the price?', thai: 'ลดหน่อยได้ไหมคะ', latinised: 'lót nɔ̀ɔi dâi mái', category: 'numbers', audio: '2023-05-25-10-26-25session4-10.mp3' },
    { prompt: 'do you want? (to take thing)', thai: 'เอาไหมคะ', latinised: 'aow mái', category: 'numbers', audio: '2023-05-25-10-27-41session4-11.mp3' },
    { prompt: 'what is your telephone number?', thai: 'โทรศัพท์ของคุณเบอร์อะไรครับ', latinised: 'too ra sàp (kɔ̌ɔng) bəə arai', category: 'numbers', audio: '2023-05-25-10-28-13session4-12.mp3' },
    { prompt: 'how old are you?', thai: 'คุณอายุเท่าไหร่คะ', latinised: 'kun aa yú tâo rài', category: 'numbers', audio: '2023-05-25-10-28-38session4-13.mp3' },
    // ── Food and Drink ──────────────────────────────────────────────
    { prompt: 'can i have some noodles please?', thai: 'ขอก๋วยเตี๋ยวหน่อยค่ะ', latinised: 'kɔ̌ɔ guái tiǎw nɔ̀ɔi', category: 'food-and-drink', audio: '2023-05-25-15-42-23session5-4.mp3' },
    { prompt: 'can i have tom yam please?', thai: 'ขอต้มยำหน่อยค่ะ', latinised: 'kɔ̌ɔ dtôm yam nɔ̀ɔi', category: 'food-and-drink', audio: '2023-05-25-15-51-19session5-5.mp3' },
    { prompt: 'what do you drink', thai: 'คุณดื่มอะไรครับ', latinised: 'kun duùm arai(?)', category: 'food-and-drink', audio: '2023-05-26-09-17-53session5-5.mp3' },
    { prompt: 'i drink hot coffee', thai: 'ผมดื่มกาแฟร้อน', latinised: 'pǒm duùm gaa fae rɔ́ɔn', category: 'food-and-drink', audio: '2023-05-26-09-19-16session5-6.mp3' },
    { prompt: 'aom drinking beer', thai: 'อ้อมดื่มเบียร์', latinised: 'aom duùm gaa bia', category: 'food-and-drink', audio: '2023-05-26-09-20-34session5-7.mp3' },
    { prompt: 'he drank orange juice', thai: 'เขาดื่มน้ำส้ม', latinised: 'káo duùm naám ŝom', category: 'food-and-drink', audio: '2023-05-26-09-23-35session5-8.mp3' },
    { prompt: '2 plates of fried rice and 1 bottle of water, please', thai: 'ขอข้าวผัด 2 จาน กับน้ำ 1 ขวดค่ะ', latinised: 'kɔ̌ɔ kâaw pàt 2 jaan gàp naám 1 kùat', category: 'food-and-drink', audio: '2023-05-26-10-05-19session5-9.mp3' },
    { prompt: 'can i have coffee without sugar please?', thai: 'ขอกาแฟไม่ใส่น้ำตาลหน่อยครับ', latinised: 'kɔ̌ɔ gaa fae mâi sài naám dtaan nɔ̀ɔi', category: 'food-and-drink', audio: '2023-05-26-10-17-11session5-5.mp3' },
    { prompt: 'what would you like to drink?', thai: 'ดื่มอะไรดีคะ?', latinised: 'dùum arai dii?', category: 'food-and-drink', audio: '2023-05-26-11-28-27session5-1.mp3' },
    // ── Days and Months ─────────────────────────────────────────────
    { prompt: 'when are you going to bangkok?', thai: 'คุณจะไปกรุงเทพฯเมื่อไหร่คะ?', latinised: 'kun jà bpai grung têep mûa rài (?)', category: 'days-and-months', audio: '2023-05-26-13-33-04session6-2.mp3' },
    { prompt: 'i will go to bangkok next month', thai: 'ผมจะไปกรุงเทพฯเดือนหน้า', latinised: 'pǒm jà bpai grung têep duan nâa', category: 'days-and-months', audio: '2023-05-26-13-35-03session6-3.mp3' },
    { prompt: 'has he ever eaten papaya salad?', thai: 'เขาเคยกินส้มตำไหม?', latinised: 'káo kəəi gin sôm dtam mái (?)', category: 'days-and-months', audio: '2023-05-26-13-38-02session6-6.mp3' },
    { prompt: 'he had already eaten papaya salad', thai: 'เขาเคยกินส้มตำแล้ว', latinised: 'káo kəəi gin sôm dtam laéw', category: 'days-and-months', audio: '2023-05-26-13-39-05session6-7.mp3' },
    { prompt: 'he has never eaten papaya salad', thai: 'เขาไม่เคยกินส้มตำ', latinised: 'káo m̂ai kəəi gin sôm dtam', category: 'days-and-months', audio: '2023-05-26-13-39-58session6-8.mp3' },
    { prompt: 'how many days do you study chinese?', thai: 'คุณเรียนภาษาจีนกี่วัน?', latinised: 'kun rian paa sǎa jiin giì wan (?)', category: 'days-and-months', audio: '2023-05-26-13-55-35session6-4.mp3' },
    { prompt: 'we study chinese for 15 days', thai: 'เราเรียนภาษาจีน 15 วัน', latinised: 'rao rian paa sǎa jiin 15 wan', category: 'days-and-months', audio: '2023-05-26-13-57-31session6-5.mp3' },
    { prompt: 'shall we go together?', thai: 'เราไปด้วยกันไหมคะ', latinised: 'rao bpai dûay gan mái (?)', category: 'days-and-months', audio: '2023-05-26-15-07-06session6-0.mp3' },
    { prompt: 'where shall we go?', thai: 'เราไปที่ไหนดีครับ', latinised: 'rao bpai tîi ňai dii (?)', category: 'days-and-months', audio: '2023-05-26-15-14-21session6-1.mp3' },
    { prompt: 'what shall we eat?', thai: 'กินอะไรดีคะ', latinised: 'gin arai dii (?)', category: 'days-and-months', audio: '2023-05-26-15-17-10session6-2.mp3' },
    { prompt: 'what is the day yesterday?', thai: 'เมื่อวานนี้วันอะไร', latinised: 'mûa waan níi wan arai (?)', category: 'days-and-months', audio: '2023-05-26-15-18-42session6-4.mp3' },
    { prompt: 'yesterday is monday', thai: 'เมื่อวานนี้วันจันทร์', latinised: 'mûa waan níi wan jan', category: 'days-and-months', audio: '2023-05-26-15-19-18session6-5.mp3' },
    { prompt: 'what is the date tomorrow?', thai: 'พรุ่งนี้วันที่เท่าไหร่ครับ?', latinised: 'prûng níi wan tîi tâo rai (?)', category: 'days-and-months', audio: '2023-05-26-15-20-41session6-6.mp3' },
    { prompt: 'tomorrow is 21st', thai: 'พรุ่งนี้วันที่ 21 ค่ะ', latinised: 'prûng níi wan tîi 21st', category: 'days-and-months', audio: '2023-05-26-15-21-13session6-7.mp3' },
    { prompt: 'what did you do yesterday', thai: 'เมื่อวานนี้คุณทำอะไร', latinised: 'mûa waan níi kun tam arai (?)', category: 'days-and-months', audio: '2023-05-26-13-12-15session6-3.mp3' },
    { prompt: 'yesterday i went swimming', thai: 'เมื่อวานนี้ผมไปว่ายน้ำครับ', latinised: 'mûa waan níi pǒm bpai wâai náam', category: 'days-and-months', audio: '2023-05-26-13-13-57session6-4.mp3' },
    // ── Period of Time ──────────────────────────────────────────────
    { prompt: 'we walk to school', thai: 'เราเดินไปโรงเรียน', latinised: 'rao dəən bpai roong rian', category: 'period-of-time', audio: '2023-05-26-16-43-34session7-7.mp3' },
    { prompt: 'call (telephone) to a friend', thai: 'โทร(ศัพท์)ไปหาเพื่อน', latinised: 'too (ra sàp) bpai hǎa pûan', category: 'period-of-time', audio: '2023-05-26-17-01-19session7-5.mp3' },
    { prompt: 'call (telephone) to a friend', thai: 'โทร(ศัพท์)มาหาเพื่อน', latinised: 'too (ra sàp) maa hǎa pûan', category: 'period-of-time', audio: '2023-05-26-17-02-09session7-6.mp3' },
    { prompt: 'after noon i went to see a friend', thai: 'ตอนเที่ยงผมไปหาเพื่อน', latinised: 'dtɔɔn tiâng pǒm bpai hǎa pûan', category: 'period-of-time', audio: '2023-05-29-09-11-31session7-7.mp3' },
    { prompt: 'in the afternoon he called his mother', thai: 'ตอนบ่ายเขาโทรไปหาแม่', latinised: 'dtɔɔn bàai káo too bpai hǎa m̂ae', category: 'period-of-time', audio: '2023-05-29-09-24-09session7-8.mp3' },
    { prompt: 'in the evening he was at home', thai: 'ตอนเย็นเขาอยู่ที่บ้าน', latinised: 'dtɔɔn yen káo yùu (tîi) bâan', category: 'period-of-time', audio: '2023-05-29-09-37-42session7-12.mp3' },
    { prompt: 'how many hours do you study english?', thai: 'คุณเรียนภาษาอังกฤษกี่ชั่วโมง', latinised: 'kun rian paa sǎa ang grìt gii (?) cĥua moong', category: 'period-of-time', audio: '2023-05-29-09-46-28session7-3.mp3' },
    { prompt: 'i study english for half an hour', thai: 'ผมเรียนภาษาอังกฤษครึ่งชั่วโมง', latinised: 'pǒm rian paa sǎa ang grìt krûng cĥua moong', category: 'period-of-time', audio: '2023-05-29-09-47-41session7-4.mp3' },
    { prompt: 'how many minutes are you on the phone?', thai: 'คุณโทรศัพท์กี่นาที', latinised: 'kun too ra sàp gìi (?) naa tii', category: 'period-of-time', audio: '2023-05-29-09-52-25session7-5.mp3' },
    { prompt: 'do you have free time?', thai: 'คุณว่างไหมคะ', latinised: 'kun wâang mái(?)', category: 'period-of-time', audio: '2023-05-29-10-25-55session7-9.mp3' },
    // ── Family ──────────────────────────────────────────────────────
    { prompt: 'how many children do you have?', thai: 'คุณมีลูกกี่คน', latinised: 'kun mii lûuk gìi(?) kon', category: 'family', audio: '2023-05-29-10-52-00session8-6.mp3' },
    { prompt: 'i have 2 children', thai: 'ผมมีลูก 2 คน', latinised: 'pǒm mii lûuk 2 kon', category: 'family', audio: '2023-05-29-10-53-00session8-7.mp3' },
    { prompt: 'how old is your child', thai: 'ลูกของคุณอายุเท่าไหร่', latinised: 'lûuk kɔ̌ɔng kun aa yú tâo rài (?)', category: 'family', audio: '2023-05-29-10-55-02session8-1.mp3' },
    { prompt: 'my child is 4 years old', thai: 'ลูกของผมอายุ 4 ปี', latinised: 'lûuk kɔ̌ɔng pǒm aa yú 4 bpii', category: 'family', audio: '2023-05-29-10-56-38session8-2.mp3' },
    { prompt: 'or not yet?', thai: 'รึยัง', latinised: 'rú yang (?)', category: 'family', audio: '2023-05-29-11-00-37session8-3.mp3' },
    { prompt: 'is he married', thai: 'เขาเเต่งงานหรือยัง', latinised: 'káo dtaèng ngaan rú yang (?)', category: 'family', audio: '2023-05-29-11-02-56session8-4.mp3' },
    { prompt: 'he is married', thai: 'เขาเเต่งงานแล้ว', latinised: 'káo dtaèng ngaan laéw', category: 'family', audio: '2023-05-29-11-05-14session8-5.mp3' },
    { prompt: 'he is not married', thai: 'เขายังไม่ได้แต่งงาน', latinised: 'káo yang m̂ai (d̂ai) dtàeng ngaan', category: 'family', audio: '2023-05-29-11-05-52session8-6.mp3' },
    { prompt: 'who likes to watch movies', thai: 'ใครชอบดูหนัง', latinised: 'krai cĥɔɔp duu nǎng(?)', category: 'family', audio: '2023-05-29-11-07-58session8-2.mp3' },
    { prompt: 'my brother likes to watch movies', thai: 'พี่ชายของผมชอบดูหนัง', latinised: 'pîi chaai (kɔ̌ɔng) pǒm cĥɔɔp duu nǎng', category: 'family', audio: '2023-05-29-11-08-51session8-3.mp3' },
    { prompt: 'who does he like to go to the movies with?', thai: 'เขาชอบไปดูหนังกับใคร', latinised: 'káo cĥɔɔp bpai duu nǎng gàp krai (?)', category: 'family', audio: '2023-05-30-09-22-46session8-4.mp3' },
    { prompt: 'he likes to go to the movies with his girlfriend', thai: 'เขาชอบไปดูหนังกับแฟน', latinised: 'káo cĥɔɔp bpai duu nǎng gàp faen', category: 'family', audio: '2023-05-30-09-23-34session8-5.mp3' },
    { prompt: 'are you married?', thai: 'คุณแต่งงานหรือยังคะ', latinised: 'kun dtàeng ngaan rú yang (?)', category: 'family', audio: '2023-05-30-09-33-38session8-0.mp3' },
    { prompt: 'do you have any child?', thai: 'คุณมีลูกหรือยังคะ', latinised: 'kun mii lûuk rú yang (?)', category: 'family', audio: '2023-05-30-09-34-11session8-1.mp3' },
    { prompt: 'have you eaten yet?', thai: 'คุณกินข้าวหรือยังคะ', latinised: 'kun gin kâaw rú yang (?)', category: 'family', audio: '2023-05-30-09-46-52session8-2.mp3' },
    // ── Occupations ─────────────────────────────────────────────────
    { prompt: 'what is your job?', thai: 'คุณทำงานอะไรคะ', latinised: 'kun tam ngaan arai (?)', category: 'occupations', audio: '2023-05-30-10-26-08session9-6.mp3' },
    { prompt: 'aom is a teacher', thai: 'อ้อมเป็นครู', latinised: 'aom bpen kruu', category: 'occupations', audio: '2023-05-30-10-26-48session9-7.mp3' },
    { prompt: 'aom teaches english', thai: 'อ้อมสอนภาษาอังกฤษ', latinised: 'aom sɔ̌ɔn paa sǎa ang grìt', category: 'occupations', audio: '2023-05-30-10-28-06session9-8.mp3' },
    { prompt: 'aom works at cmu', thai: 'อ้อมทำงานที่ ม.ช.', latinised: 'aom tam ngaan (tîi) mɔɔ chɔɔ', category: 'occupations', audio: '2023-05-30-10-28-42session9-9.mp3' },
    { prompt: 'why are you a nurse', thai: 'ทำไมคุณเป็นพยาบาล', latinised: 'tam mai(?) bpen pa yaa baan', category: 'occupations', audio: '2023-05-30-10-47-04session9-2.mp3' },
    { prompt: 'he became a nurse because he wanted to help people', thai: 'เขาเป็นพยาบาลเพราะว่าอยากช่วยคน', latinised: 'káo bpen pa yaa baan pŕɔ wâa yàak chûai kon', category: 'occupations', audio: '2023-05-30-10-48-43session9-3.mp3' },
    { prompt: 'what do you do?', thai: 'คุณทำงานอะไรคะ', latinised: 'kun tam ngaan arai (?)', category: 'occupations', audio: '2023-05-31-10-40-00session9-8.mp3' },
    { prompt: 'he is retired', thai: 'เขาเกษียณแล้ว', latinised: 'káo gà sǐan láew', category: 'occupations', audio: '2023-05-31-10-52-19session9-11.mp3' },
    // ── Fruits ──────────────────────────────────────────────────────
    { prompt: 'do you like bananas or oranges?', thai: 'คุณชอบกล้วยหรือส้ม', latinised: 'kun cĥɔɔp glûai rǔu(?) sôm', category: 'fruits', audio: '2023-05-31-11-04-55session10-7.mp3' },
    { prompt: 'i like orange', thai: 'ผมชอบส้ม', latinised: 'pǒm cĥɔɔp sôm', category: 'fruits', audio: '2023-05-31-11-07-50session10-8.mp3' },
    { prompt: 'he likes sour mangoes', thai: 'เขาชอบมะม่วงเปรี้ยว', latinised: 'káo cĥɔɔp má mûang bpriâw', category: 'fruits', audio: '2023-05-31-11-11-06session10-4.mp3' },
    { prompt: 'i like ripe mangoes', thai: 'ผมชอบมะม่วงสุก', latinised: 'pǒm cĥɔɔp má mûang sùk', category: 'fruits', audio: '2023-05-31-11-12-17session10-5.mp3' },
    { prompt: 'what’s the most fruit do you like ?', thai: 'คุณชอบผลไม้อะไรที่สุด', latinised: 'kun cĥɔɔp pǒn la mái arai(?) tîi sùt', category: 'fruits', audio: '2023-05-31-11-34-49session10-0.mp3' },
    // ── Feeling and Adjective ───────────────────────────────────────
    { prompt: 'why is he crying', thai: 'ทำไมเขาร้องไห้', latinised: 'tam mai(?) káo rɔ́ɔng hâai', category: 'feeling-and-adjective', audio: '2023-05-31-14-11-12session11-5.mp3' },
    { prompt: 'he cried because he was sorry', thai: 'เขาร้องไห้เพราะว่าเขาเสียใจ', latinised: 'káo rɔ́ɔng hâai pŕɔ (wâa) sǐa jai', category: 'feeling-and-adjective', audio: '2023-05-31-14-12-21session11-6.mp3' },
    // ── Color ───────────────────────────────────────────────────────
    { prompt: 'he like blue (light) more than green', thai: 'เขาชอบสีฟ้ามากกว่าสีเขียว', latinised: 'káo cĥɔɔp sǐi fáa mâak gwàa sǐi kěaw', category: 'color', audio: '2023-08-31-14-54-35session12-9.mp3' },
    { prompt: 'what color do you like the most?', thai: 'คุณชอบสีอะไรที่สุด', latinised: 'kun cĥɔɔp sǐi arai(?) tîi sùt', category: 'color', audio: '2023-08-31-15-01-33session12-12.mp3' },
    { prompt: 'i like black the most', thai: 'ผมชอบสีดำที่สุด', latinised: 'pǒm cĥɔɔp sǐi dam tîi sùt', category: 'color', audio: '2023-08-31-15-05-21session12-13.mp3' },
    { prompt: 'what color do you like most?', thai: 'คุณชอบสีอะไรที่สุดคะ', latinised: 'cĥɔɔp sǐi arai tîi sùt ? k', category: 'color', audio: '2023-08-31-16-20-51session12-26.mp3' },
    { prompt: 'when you see the traffic light then turn left', thai: 'เจอไฟแดงแล้วก็เลี้ยวซ้าย', latinised: 'jəəfai daeng lágɔ̂ɔliáw sáai k', category: 'color', audio: '2023-08-31-16-22-13session12-27.mp3' },
    { prompt: 'you are the most beautiful', thai: 'สวยที่สุด', latinised: 'sǔay tîi sùt', category: 'color', audio: '2023-08-31-16-24-24session12-30.mp3' },
    // ── Parts of Body ───────────────────────────────────────────────
    { prompt: 'he has a headache', thai: 'เขาปวดหัว', latinised: 'káo bpuàt hǔa', category: 'parts-of-body', audio: '2023-09-12-11-31-00session13-21.mp3' },
    { prompt: 'he has a toothache', thai: 'เขาปวดฟัน', latinised: 'káo bpuàt fan', category: 'parts-of-body', audio: '2023-09-12-11-32-11session13-22.mp3' },
    { prompt: 'he has a back', thai: 'เขาปวดหลัง', latinised: 'káo bpuàt lǎng', category: 'parts-of-body', audio: '2023-09-12-11-40-33session13-23.mp3' },
    { prompt: 'he has a stomach', thai: 'เขาปวดท้อง', latinised: 'káo bpuàt tɔ́ɔng', category: 'parts-of-body', audio: '2023-09-12-11-42-06session13-24.mp3' },
    { prompt: 'his eyes hurt', thai: 'เขาเจ็บตา', latinised: 'káo jèp dtaa', category: 'parts-of-body', audio: '2023-09-12-11-45-03session13-25.mp3' },
    { prompt: 'he broke his arm', thai: 'เขาแขนหัก', latinised: 'káo kǎen hàk', category: 'parts-of-body', audio: '2023-09-12-11-47-50session13-28.mp3' },
    { prompt: 'he broke his leg', thai: 'เขาขาหัก', latinised: 'káo kǎa hàk', category: 'parts-of-body', audio: '2023-09-12-11-48-41session13-29.mp3' },
    { prompt: 'he is heartbroken', thai: 'เขาอกหัก', latinised: 'káo òk hàk', category: 'parts-of-body', audio: '2023-09-12-11-50-47session13-30.mp3' },
    { prompt: 'he has diarrhea', thai: 'เขาท้องเสีย', latinised: 'káo tɔ́ɔng sǐa', category: 'parts-of-body', audio: '2023-09-12-11-55-29session13-33.mp3' },
    { prompt: 'he has a cold', thai: 'เขาเป็นหวัด', latinised: 'káo pen wàt', category: 'parts-of-body', audio: '2023-09-12-11-58-45session13-37.mp3' },
    { prompt: 'he has a fever', thai: 'เขาเป็นไข้', latinised: 'káo pen k̂ai', category: 'parts-of-body', audio: '2023-09-12-11-59-35session13-38.mp3' },
    { prompt: 'he has a cancer', thai: 'เขาเป็นมะเร็ง', latinised: 'káo pen ma reng', category: 'parts-of-body', audio: '2023-09-12-12-00-29session13-39.mp3' },
    { prompt: 'whats wrong with you?', thai: 'คุณเป็นอะไรคะ?', latinised: 'kun bpen arai ká', category: 'parts-of-body', audio: '2023-09-12-15-03-42session13-60.mp3' },
    { prompt: 'he is not feeling well', thai: 'เขาไม่ค่อยสบายค่ะ', latinised: 'káo m̂ai kɔ̂ɔi sa baai kà', category: 'parts-of-body', audio: '2023-09-12-15-06-48session13-61.mp3' },
    { prompt: 'is it better?', thai: 'ดีขึ้นไหมคะ', latinised: 'dii k̂un m̂ai ká', category: 'parts-of-body', audio: '2023-09-12-15-09-14session13-62.mp3' },
    { prompt: 'it is better', thai: 'ดีขึ้นค่ะ', latinised: 'dii k̂un ká', category: 'parts-of-body', audio: '2023-09-12-15-15-05session13-63.mp3' },
    { prompt: 'it is gone', thai: 'หายแล้วครับ', latinised: 'hǎai læ̂w kráp', category: 'parts-of-body', audio: '2023-09-12-15-18-03session13-64.mp3' },
    { prompt: 'have you taken medicine yet?', thai: 'คุณกินยารึยังครับ', latinised: 'kun gin yaa ru yang kráp', category: 'parts-of-body', audio: '2023-09-12-15-22-14session13-65.mp3' },
    { prompt: 'have you gone to the doctor yet?', thai: 'คุณไปหาหมอรึยังคะ', latinised: 'kun bpai hǎa m̌ɔɔ rúyang ka', category: 'parts-of-body', audio: '2023-09-12-15-26-56session13-66.mp3' },
    { prompt: 'has he recovered yet?', thai: 'เขาหายรึยัง?', latinised: 'káo hǎai rú yang', category: 'parts-of-body', audio: '2023-09-12-15-29-38session13-67.mp3' },
    // ── Transportation ──────────────────────────────────────────────
    { prompt: 'you come to school', thai: 'คุณมาโรงเรียน', latinised: 'kun maa roong rian', category: 'transportation', audio: '2023-09-12-15-43-58session14-6.mp3' },
    { prompt: 'he rides a motorcycle to school', thai: 'เขาขี่มอเตอร์ไซค์มาโรงเรียน', latinised: 'káo kìi mɔɔdtəəsai maa roong rian', category: 'transportation', audio: '2023-09-12-15-51-04session14-8.mp3' },
    { prompt: 'he drove to school', thai: 'เขาขับรถมาโรงเรียน', latinised: 'káo kàp rót maa roong rian', category: 'transportation', audio: '2023-09-12-15-52-56session14-9.mp3' },
    { prompt: 'he rode a red car to school', thai: 'เขานั่งรถแดงมาโรงเรียน', latinised: 'káo nạ̀ng rót daeng maa roong rian', category: 'transportation', audio: '2023-09-12-15-55-52session14-10.mp3' },
    { prompt: 'where did you book your plane tickets?', thai: 'คุณจองตั๋วเครื่องบินที่ไหนคะ', latinised: 'kun jɔɔng dtǔa dâi tíi nǎi ká', category: 'transportation', audio: '2023-09-12-15-59-52session14-13.mp3' },
    { prompt: 'where do you rent bicycles?', thai: 'คุณเช่าจักรยานที่ไหนครับ', latinised: 'kun châo jàk gr̀a yaan tíi nǎi ká kráp', category: 'transportation', audio: '2023-09-12-16-02-29session14-14.mp3' },
    { prompt: 'when does the train leave bangkok?', thai: 'รถไฟออกจากกรุงเทพเมื่อไหร่คะ', latinised: 'rót fai ɔɔ̀k jaàk grung têep mûa rài ká', category: 'transportation', audio: '2023-09-12-16-06-08session14-18.mp3' },
    { prompt: 'when does the train arrive in bangkok?', thai: 'รถไฟมาถึงกรุงเทพเมื่อไหร่คะ', latinised: 'rót fai maa tǔng grung têep mûa rài ká', category: 'transportation', audio: '2023-09-12-16-07-22session14-19.mp3' },
    { prompt: 'where can i reserve tickets?', thai: 'ผมจองตั๋วได้ที่ไหนครับ', latinised: 'pǒm jɔɔng dtǔa dâi tíi nǎi kráp', category: 'transportation', audio: '2023-09-12-17-03-09session14-40.mp3' },
    { prompt: 'when does the train leave?', thai: 'รถไฟออกเมื่อไหร่ครับ', latinised: 'rót fai ɔɔ̀k mûa rài kráp', category: 'transportation', audio: '2023-09-12-17-04-18session14-41.mp3' },
    { prompt: 'when do you arrive in bangkok?', thai: 'คุณถึงกรุงเทพเมื่อไหร่ครับ', latinised: 'kun tǔng grung têep mûa rài kráp', category: 'transportation', audio: '2023-09-12-17-05-06session14-42.mp3' },
    { prompt: 'do you want me to send it?', thai: 'ให้ผมไปส่งไหมครับ', latinised: '(ĥai) pǒm bpai sòng mái kráp', category: 'transportation', audio: '2023-09-12-17-07-06session14-44.mp3' },
];
