export type ExerciseCategory = 'greeting' | 'places' | 'activity' | 'numbers' | 'food-and-drink' | 'days-and-months' | 'period-of-time';

export const EXERCISE_CATEGORIES: { id: ExerciseCategory; label: string }[] = [
    { id: 'greeting', label: 'Greeting' },
    { id: 'places', label: 'Places' },
    { id: 'activity', label: 'Activity' },
    { id: 'numbers', label: 'Numbers' },
    { id: 'food-and-drink', label: 'Food and Drink' },
    { id: 'days-and-months', label: 'Days and Months' },
    { id: 'period-of-time', label: 'Period of Time' },
];

export interface Exercise {
    prompt: string;
    thai: string;
    latinised: string;
    category: ExerciseCategory;
}

export const EXERCISES: Exercise[] = [
    // ── Greeting ───────────────────────────────────────────────────────────
    { prompt: 'I want to eat pad thai', thai: 'อยากกินผัดไทย', latinised: 'yàak gin phàt thai', category: 'greeting' },
    { prompt: 'I want to go to the market', thai: 'อยากไปตลาด', latinised: 'yàak bpai dta làat', category: 'greeting' },
    { prompt: 'Can you speak Thai?', thai: 'พูดภาษาไทยได้ไหม', latinised: 'phûut phaasǎa thai dâi mǎi', category: 'greeting' },
    { prompt: "I can't eat spicy food", thai: 'กินเผ็ดไม่ได้', latinised: 'gin phèt mâi dâi', category: 'greeting' },
    { prompt: 'You should try green curry', thai: 'ควรลองแกงเขียวหวาน', latinised: 'khuuan lawng gaeng khǐaw wǎan', category: 'greeting' },
    { prompt: 'I must go now', thai: 'ต้องไปแล้ว', latinised: 'dtông bpai láew', category: 'greeting' },
    { prompt: 'I like eating Thai food', thai: 'ชอบกินอาหารไทย', latinised: 'chôop gin aa hǎan thai', category: 'greeting' },
    { prompt: 'Can you help me?', thai: 'ช่วยได้ไหม', latinised: 'chûai dâi mǎi', category: 'greeting' },
    { prompt: 'I want to buy this', thai: 'อยากซื้ออันนี้', latinised: 'yàak súe an nîi', category: 'greeting' },
    { prompt: "I don't want it spicy", thai: 'ไม่เอาเผ็ด', latinised: 'mâi ao phèt', category: 'greeting' },
    { prompt: 'I have to go home', thai: 'ต้องกลับบ้าน', latinised: 'dtông glàp bâan', category: 'greeting' },
    { prompt: 'Do you want to eat together?', thai: 'อยากกินข้าวด้วยกันไหม', latinised: 'yàak gin khâao dûai gan mǎi', category: 'greeting' },
    { prompt: 'I should try this', thai: 'ควรลองอันนี้', latinised: 'khuuan lawng an nîi', category: 'greeting' },
    { prompt: 'I like going for walks', thai: 'ชอบไปเดินเล่น', latinised: 'chôop bpai dooen lên', category: 'greeting' },
    { prompt: 'Please speak slowly', thai: 'ช่วยพูดช้าช้าหน่อย', latinised: 'chûai phûut cháa cháa nòi', category: 'greeting' },
    { prompt: 'Is that true?', thai: 'จริงเหรอ', latinised: 'jing rǔe', category: 'greeting' },
    { prompt: 'That is true.', thai: 'จริงจริง', latinised: 'jing jing', category: 'greeting' },
    // ── Places ─────────────────────────────────────────────────────────────
    { prompt: 'Where is the train station?', thai: 'สถานีรถไฟอยู่ที่ไหน', latinised: 'sà thǎa nii rót fai yùu thîi nǎi', category: 'places' },
    { prompt: 'Turn left at the market', thai: 'เลี้ยวซ้ายที่ตลาด', latinised: 'líaw sáai thîi dta làat', category: 'places' },
    { prompt: 'Go straight then turn right', thai: 'ตรงไปแล้วเลี้ยวขวา', latinised: 'dtrong bpai láew líaw khwǎa', category: 'places' },
    { prompt: 'The temple is near the river', thai: 'วัดอยู่ใกล้แม่น้ำ', latinised: 'wát yùu glâi mâe nám', category: 'places' },
    { prompt: 'Is it far?', thai: 'ไกลไหม', latinised: 'glai mǎi', category: 'places' },
    { prompt: 'The bank is next to the market', thai: 'ธนาคารอยู่ข้างๆตลาด', latinised: 'thá naa khaan yùu khâang khâang dta làat', category: 'places' },
    { prompt: 'Where is the hotel?', thai: 'โรงแรมอยู่ที่ไหน', latinised: 'roong raem yùu thîi nǎi', category: 'places' },
    { prompt: 'Where are you going?', thai: 'ไปไหน', latinised: 'bpai nǎi', category: 'places' },
    { prompt: 'I want to go to Bangkok', thai: 'อยากไปกรุงเทพฯ', latinised: 'yàak bpai grung thêep', category: 'places' },
    { prompt: "It's on the left side", thai: 'อยู่ทางซ้าย', latinised: 'yùu thaang sáai', category: 'places' },
    { prompt: "It's on the right side", thai: 'อยู่ทางขวา', latinised: 'yùu thaang khwǎa', category: 'places' },
    { prompt: 'The airport is far', thai: 'สนามบินอยู่ไกล', latinised: 'sà nǎam bin yùu glai', category: 'places' },
    { prompt: 'Is the police station near?', thai: 'สถานีตำรวจอยู่ใกล้ไหม', latinised: 'sà thǎa nii dtam rùat yùu glâi mǎi', category: 'places' },
    { prompt: 'The hotel is opposite the temple', thai: 'โรงแรมอยู่ตรงข้ามวัด', latinised: 'roong raem yùu dtrong khâam wát', category: 'places' },
    { prompt: 'Go straight on this road', thai: 'ตรงไปถนนนี้', latinised: 'dtrong bpai thà nǒn níi', category: 'places' },
    { prompt: 'Where is the bathroom?', thai: 'ห้องน้ำอยู่ที่ไหน', latinised: 'hông nám yùu thîi nǎi', category: 'places' },
    { prompt: 'The bathroom is here.', thai: 'ห้องน้ำอยู่ที่นี่', latinised: 'hông nám yùu thîi nîi', category: 'places' },
    { prompt: 'The restaurant is near the hotel.', thai: 'ร้านอาหารอยู่ใกล้โรงแรม', latinised: 'ráan aa hǎan yùu glâi roong raem', category: 'places' },
    { prompt: 'Chiang Mai University is opposite the mountain.', thai: 'มหาวิทยาลัยเชียงใหม่อยู่ตรงข้ามภูเขา', latinised: 'má hǎa wít thá yaa lái chiang mài yùu dtrong khâam phuu kháo', category: 'places' },
    { prompt: 'I like to go to the sea very much.', thai: 'ผมชอบไปทะเลมาก', latinised: 'pǒm chôop bpai thá leh mâak', category: 'places' },
    { prompt: 'He doesn\'t like to go to the hospital.', thai: 'เขาไม่ชอบไปโรงพยาบาล', latinised: 'kháo mâi chôop bpai roong phá yaa baan', category: 'places' },
    { prompt: 'Go straight then turn left.', thai: 'ตรงไปแล้วเลี้ยวซ้าย', latinised: 'dtrong bpai láew líaw sáai', category: 'places' },
    { prompt: 'Where is a Thai restaurant?', thai: 'ร้านอาหารไทยอยู่ที่ไหน', latinised: 'ráan aa hǎan thai yùu thîi nǎi', category: 'places' },
    { prompt: 'Turn right at the hospital.', thai: 'เลี้ยวขวาที่โรงพยาบาล', latinised: 'líaw khwǎa thîi roong phá yaa baan', category: 'places' },
    { prompt: 'Where do you like to take a trip?', thai: 'คุณชอบไปเที่ยวที่ไหน', latinised: 'khun chôop bpai thîaw thîi nǎi', category: 'places' },
    { prompt: 'She likes to go to the waterfall.', thai: 'เขาชอบไปน้ำตก', latinised: 'kháo chôop bpai nám dtòk', category: 'places' },
    { prompt: 'Where have you been?', thai: 'ไปไหนมา', latinised: 'bpai nǎi maa', category: 'places' },
    { prompt: 'This one comes from Japan.', thai: 'อันนี้มาจากญี่ปุ่น', latinised: 'an nîi maa jàak yîi bpùn', category: 'places' },
    // ── Activity ───────────────────────────────────────────────────────────
    { prompt: 'Where are you going?', thai: 'คุณไปไหน', latinised: 'khun bpai nǎi', category: 'activity' },
    { prompt: 'We go to work.', thai: 'เราไปทำงาน', latinised: 'rao bpai tham ngaan', category: 'activity' },
    { prompt: 'I like to see movie.', thai: 'ผมชอบดูหนัง', latinised: 'pǒm chôop duu nǎng', category: 'activity' },
    { prompt: 'I like to eat Thai food too.', thai: 'ผมชอบกินอาหารไทยด้วย', latinised: 'pǒm chôop gin aa hǎan thai dûai', category: 'activity' },
    { prompt: 'Shall we go to walk together?', thai: 'ไปเดินเล่นด้วยกันไหม', latinised: 'bpai dooen lên dûai gan mǎi', category: 'activity' },
    { prompt: 'I don\'t know.', thai: 'ไม่รู้', latinised: 'mâi rúu', category: 'activity' },
    { prompt: 'I want to dance with you.', thai: 'ผมอยากเต้นกับคุณ', latinised: 'pǒm yàak dtên gàp khun', category: 'activity' },
    { prompt: 'He does not want to sleep.', thai: 'เขาไม่อยากนอน', latinised: 'kháo mâi yàak nawn', category: 'activity' },
    { prompt: 'Can you speak English?', thai: 'คุณพูดภาษาอังกฤษได้ไหม', latinised: 'khun phûut phaa sǎa ang grìt dâi mǎi', category: 'activity' },
    { prompt: 'I can speak a little bit Thai.', thai: 'ผมพูดภาษาไทยได้นิดหน่อย', latinised: 'pǒm phûut phaa sǎa thai dâi nít nòi', category: 'activity' },
    { prompt: 'Say again please.', thai: 'พูดอีกที', latinised: 'phûut ìik thii', category: 'activity' },
    { prompt: 'We like to eat Japanese food so much.', thai: 'เราชอบกินอาหารญี่ปุ่นมาก', latinised: 'rao chôop gin aa hǎan yîi bpùn mâak', category: 'activity' },
    { prompt: 'Speak slowly please.', thai: 'พูดช้าช้าหน่อย', latinised: 'phûut cháa cháa nòi', category: 'activity' },
    { prompt: 'She swims very well.', thai: 'เขาว่ายน้ำเก่งมาก', latinised: 'kháo wâai nám gèng mâak', category: 'activity' },
    { prompt: 'Can you swim?', thai: 'คุณว่ายน้ำได้ไหม', latinised: 'khun wâai nám dâi mǎi', category: 'activity' },
    { prompt: 'Can you dance with me?', thai: 'คุณเต้นกับผมได้ไหม', latinised: 'khun dtên gàp pǒm dâi mǎi', category: 'activity' },
    // ── Numbers ────────────────────────────────────────────────────────────
    { prompt: 'What is your telephone number?', thai: 'โทรศัพท์เบอร์อะไร', latinised: 'thoo rá sàp boe à rai', category: 'numbers' },
    { prompt: 'My telephone number is 081-234-9765.', thai: 'โทรศัพท์เบอร์ศูนย์แปดหนึ่งสองสามสี่เก้าเจ็ดหกห้า', latinised: 'thoo rá sàp boe sǔun bpàet nùeng sǎawng sǎam sìi gâo jèt hòk hâa', category: 'numbers' },
    { prompt: 'How old are you?', thai: 'คุณอายุเท่าไร', latinised: 'khun aa yú thâo rài', category: 'numbers' },
    { prompt: 'I am 68 years old.', thai: 'ผมอายุหกสิบแปดปี', latinised: 'pǒm aa yú hòk sìp bpàet bpii', category: 'numbers' },
    { prompt: 'This one is 125 baht.', thai: 'อันนี้หนึ่งร้อยยี่สิบห้าบาท', latinised: 'an nîi nùeng rói yîi sìp hâa bàat', category: 'numbers' },
    { prompt: 'How many baht is that one?', thai: 'อันนั้นกี่บาท', latinised: 'an nán gìi bàat', category: 'numbers' },
    { prompt: 'It is very expensive.', thai: 'แพงมาก', latinised: 'phaeng mâak', category: 'numbers' },
    { prompt: 'Can you reduce the price?', thai: 'ลดหน่อยได้ไหม', latinised: 'lót nòi dâi mǎi', category: 'numbers' },
    // ── Food and Drink ─────────────────────────────────────────────────────
    { prompt: 'I take this one.', thai: 'เอาอันนี้', latinised: 'ao an nîi', category: 'food-and-drink' },
    { prompt: "I'd like fried rice, please", thai: 'ขอข้าวผัดครับ', latinised: 'khǒo khâao phàt kráp', category: 'food-and-drink' },
    { prompt: 'I like spicy food.', thai: 'ผมชอบอาหารเผ็ด', latinised: 'pǒm chôop aa hǎan phèt', category: 'food-and-drink' },
    { prompt: 'Not too spicy, please', thai: 'ไม่เผ็ดมาก', latinised: 'mâi phèt mâak', category: 'food-and-drink' },
    { prompt: 'A little spicy', thai: 'เผ็ดนิดหน่อย', latinised: 'phèt nít nòi', category: 'food-and-drink' },
    { prompt: 'With egg, please', thai: 'ใส่ไข่ด้วย', latinised: 'sài khài dûai', category: 'food-and-drink' },
    { prompt: 'No sugar', thai: 'ไม่ใส่น้ำตาล', latinised: 'mâi sài nám dtaan', category: 'food-and-drink' },
    { prompt: 'Eat here', thai: 'กินที่นี่', latinised: 'gin thîi nîi', category: 'food-and-drink' },
    { prompt: 'Take away', thai: 'กลับบ้าน', latinised: 'glàp bâan', category: 'food-and-drink' },
    { prompt: 'Check, please', thai: 'เก็บเงินด้วย', latinised: 'gèp ngoen dûai', category: 'food-and-drink' },
    { prompt: 'How much is this?', thai: 'อันนี้เท่าไร', latinised: 'an nîi thâo rài', category: 'food-and-drink' },
    { prompt: 'One green curry with rice', thai: 'ขอแกงเขียวหวานหนึ่งจานกับข้าว', latinised: 'khǒo gaeng khǐaw wǎan nùeng jaan gàp khâao', category: 'food-and-drink' },
    { prompt: 'Is it delicious?', thai: 'อร่อยไหม', latinised: 'à ròi mǎi', category: 'food-and-drink' },
    { prompt: 'Very delicious!', thai: 'อร่อยมาก', latinised: 'à ròi mâak', category: 'food-and-drink' },
    { prompt: 'One more beer, please', thai: 'ขอเบียร์อีกหนึ่งขวด', latinised: 'khǒo bia ìik nùeng khùat', category: 'food-and-drink' },
    { prompt: 'Water, please', thai: 'ขอน้ำครับ', latinised: 'khǒo nám kráp', category: 'food-and-drink' },
    { prompt: 'I want pad thai with egg', thai: 'เอาผัดไทยใส่ไข่', latinised: 'ao phàt thai sài khài', category: 'food-and-drink' },
    { prompt: 'What would you like to drink?', thai: 'ดื่มอะไรดี', latinised: 'dùum à rai dii', category: 'food-and-drink' },
    { prompt: 'May I have noodle soup?', thai: 'ขอก๋วยเตี๋ยวน้ำ', latinised: 'khǒo gǔai dtǐaw nám', category: 'food-and-drink' },
    { prompt: 'May I have 2 plates of rice.', thai: 'ขอข้าวสองจาน', latinised: 'khǒo khâao sǎawng jaan', category: 'food-and-drink' },
    { prompt: 'He does not like spicy food.', thai: 'เขาไม่ชอบอาหารเผ็ด', latinised: 'kháo mâi chôop aa hǎan phèt', category: 'food-and-drink' },
    { prompt: 'Iced tea with milk.', thai: 'ชาเย็นใส่นม', latinised: 'chaa yen sài nom', category: 'food-and-drink' },
    { prompt: 'Would you like to drink coffee?', thai: 'อยากดื่มกาแฟไหม', latinised: 'yàak dùum gaa fae mǎi', category: 'food-and-drink' },
    { prompt: 'May I have hot coffee without sugar?', thai: 'ขอกาแฟร้อนไม่ใส่น้ำตาล', latinised: 'khǒo gaa fae rón mâi sài nám dtaan', category: 'food-and-drink' },
    { prompt: 'I like rice with fried egg so much.', thai: 'ผมชอบข้าวกับไข่ดาวมาก', latinised: 'pǒm chôop khâao gàp khài daao mâak', category: 'food-and-drink' },
    { prompt: 'Orange juice without ice.', thai: 'น้ำส้มไม่ใส่น้ำแข็ง', latinised: 'nám sôm mâi sài nám khǎeng', category: 'food-and-drink' },
    { prompt: 'Keep the change.', thai: 'ไม่ต้องทอน', latinised: 'mâi dtông thon', category: 'food-and-drink' },
    { prompt: 'He does not eat beef.', thai: 'เขาไม่กินเนื้อ', latinised: 'kháo mâi gin núea', category: 'food-and-drink' },
    { prompt: 'May I have 2 bottles of Singha beer?', thai: 'ขอเบียร์สิงห์สองขวด', latinised: 'khǒo bia sǐng sǎawng khùat', category: 'food-and-drink' },
    { prompt: "Let's eat together.", thai: 'มากินข้าวด้วยกัน', latinised: 'maa gin khâao dûai gan', category: 'food-and-drink' },
    { prompt: 'Take away please.', thai: 'ใส่ถุงด้วย', latinised: 'sài thǔng dûai', category: 'food-and-drink' },
    { prompt: 'Can you eat spicy food?', thai: 'คุณกินอาหารเผ็ดได้ไหม', latinised: 'khun gin aa hǎan phèt dâi mǎi', category: 'food-and-drink' },
    { prompt: 'I cannot eat spicy food.', thai: 'ผมกินอาหารเผ็ดไม่ได้', latinised: 'pǒm gin aa hǎan phèt mâi dâi', category: 'food-and-drink' },
    // ── Days and Months ────────────────────────────────────────────────────
    { prompt: 'Westerners do not like Monday.', thai: 'ฝรั่งไม่ชอบวันจันทร์', latinised: 'fà ràng mâi chôop wan jan', category: 'days-and-months' },
    { prompt: 'What day is today?', thai: 'วันนี้วันอะไร', latinised: 'wan níi wan à rai', category: 'days-and-months' },
    { prompt: 'Yesterday was Monday.', thai: 'เมื่อวานนี้วันจันทร์', latinised: 'mûea waan níi wan jan', category: 'days-and-months' },
    { prompt: 'Tomorrow is the 21st.', thai: 'พรุ่งนี้วันที่ยี่สิบเอ็ด', latinised: 'phrûng nîi wan thîi yîi sìp èt', category: 'days-and-months' },
    // ── Period of Time ─────────────────────────────────────────────────────
    { prompt: 'Have you ever been to Koh Samui?', thai: 'คุณเคยไปเกาะสมุยไหม', latinised: 'khun koei bpai kòh sà mǔi mǎi', category: 'period-of-time' },
    { prompt: 'I have been to Koh Samui.', thai: 'เคยไปเกาะสมุย', latinised: 'koei bpai kòh sà mǔi', category: 'period-of-time' },
    { prompt: 'She has never eaten papaya salad.', thai: 'เขาไม่เคยกินส้มตำ', latinised: 'kháo mâi koei gin sôm dtam', category: 'period-of-time' },
    { prompt: 'What did you do yesterday?', thai: 'เมื่อวานนี้ทำอะไร', latinised: 'mûea waan níi tham à rai', category: 'period-of-time' },
    { prompt: 'What will you do tomorrow?', thai: 'พรุ่งนี้จะทำอะไร', latinised: 'phrûng nîi jà tham à rai', category: 'period-of-time' },
    { prompt: 'We went to the temple last week.', thai: 'เราไปวัดอาทิตย์ที่แล้ว', latinised: 'rao bpai wát aa thít thîi láew', category: 'period-of-time' },
    { prompt: 'I drink coffee every day.', thai: 'ผมดื่มกาแฟทุกวัน', latinised: 'pǒm dùum gaa fae thúk wan', category: 'period-of-time' },
    { prompt: 'I came to Chiang Mai 2 years ago.', thai: 'ผมมาเชียงใหม่สองปีที่แล้ว', latinised: 'pǒm maa chiang mài sǎawng bpii thîi láew', category: 'period-of-time' },
    { prompt: 'When will you study Thai?', thai: 'คุณจะเรียนภาษาไทยเมื่อไหร่', latinised: 'khun jà rian phaa sǎa thai mûea rài', category: 'period-of-time' },
    { prompt: 'He was very drunk last Monday.', thai: 'เขาเมามากวันจันทร์ที่แล้ว', latinised: 'kháo mao mâak wan jan thîi láew', category: 'period-of-time' },
    { prompt: 'I will have a girlfriend this year.', thai: 'ผมจะมีแฟนปีนี้', latinised: 'pǒm jà mii faen bpii níi', category: 'period-of-time' },
];
