export interface VocabItem {
    latinised: string;
    thai: string;
    type: 'word' | 'expression';
    english: string;
    grammar: string;
}

export const VOCABULARY: VocabItem[] = [
    { latinised: 'sà baai', thai: 'สบาย', type: 'word', english: 'well / comfortable', grammar: 'adjective' },
    { latinised: 'sà baai dii mǎi', thai: 'สบายดีไหม', type: 'expression', english: 'how are you?', grammar: 'phrase' },
    { latinised: 'mâi sà baai', thai: 'ไม่สบาย', type: 'expression', english: 'not well / sick', grammar: 'phrase' },
    { latinised: 'pǒm', thai: 'ผม', type: 'word', english: 'I (male)', grammar: 'pronoun' },
    { latinised: 'dì chǎn', thai: 'ดิฉัน', type: 'word', english: 'I (female)', grammar: 'pronoun' },
    { latinised: 'kháo', thai: 'เขา', type: 'word', english: 'he / she / they', grammar: 'pronoun' },
    { latinised: 'khun', thai: 'คุณ', type: 'word', english: 'you', grammar: 'pronoun' },
    { latinised: 'kráp', thai: 'ครับ', type: 'word', english: 'polite particle (male)', grammar: 'particle' },
    { latinised: 'khâ', thai: 'ค่ะ', type: 'word', english: 'polite particle (female / statement)', grammar: 'particle' },
    { latinised: 'ká', thai: 'คะ', type: 'word', english: 'polite particle (female / question)', grammar: 'particle' },
    { latinised: 'bprà thêet', thai: 'ประเทศ', type: 'word', english: 'country', grammar: 'noun' },
    { latinised: 'mueang', thai: 'เมือง', type: 'word', english: 'city / town', grammar: 'noun' },
    { latinised: 'jang wàt', thai: 'จังหวัด', type: 'word', english: 'province', grammar: 'noun' },
    { latinised: 'rát', thai: 'รัฐ', type: 'word', english: 'state', grammar: 'noun' },
    { latinised: 'maa jàak', thai: 'มาจาก', type: 'expression', english: 'come from', grammar: 'phrase' },
    { latinised: 'nǎao', thai: 'หนาว', type: 'word', english: 'cold (feeling)', grammar: 'adjective' },
    { latinised: 'yen', thai: 'เย็น', type: 'word', english: 'cold / cool', grammar: 'adjective' },
    { latinised: 'khâo', thai: 'เข้า', type: 'word', english: 'to enter', grammar: 'verb' },
    { latinised: 'jai', thai: 'ใจ', type: 'word', english: 'heart / mind', grammar: 'noun' },
    { latinised: 'khâo jai', thai: 'เข้าใจ', type: 'expression', english: 'to understand', grammar: 'verb' },
    { latinised: 'à ròi', thai: 'อร่อย', type: 'word', english: 'delicious', grammar: 'adjective' },
    { latinised: 'phèt', thai: 'เผ็ด', type: 'word', english: 'spicy', grammar: 'adjective' },
    { latinised: 'khǒo thôot', thai: 'ขอโทษ', type: 'expression', english: 'sorry / excuse me', grammar: 'phrase' },
    { latinised: 'khòop khun', thai: 'ขอบคุณ', type: 'expression', english: 'thank you', grammar: 'phrase' },
    { latinised: 'mâi bpen rai', thai: 'ไม่เป็นไร', type: 'expression', english: 'no problem / never mind', grammar: 'phrase' },
    { latinised: 'láew khun là', thai: 'แล้วคุณล่ะ', type: 'expression', english: 'and you? / how about you?', grammar: 'phrase' },
    { latinised: 'à rai', thai: 'อะไร', type: 'word', english: 'what', grammar: 'pronoun' },
    { latinised: 'yin dii thîi dâi rúu jàk', thai: 'ยินดีที่ได้รู้จัก', type: 'expression', english: 'pleased to meet you', grammar: 'phrase' },
    { latinised: 'phóp gan mài', thai: 'พบกันใหม่', type: 'expression', english: 'see you again', grammar: 'phrase' },
    { latinised: 'phûut ìik thii', thai: 'พูดอีกที', type: 'expression', english: 'say it again', grammar: 'phrase' },
    { latinised: 'phûut cháa cháa nòi', thai: 'พูดช้าช้าหน่อย', type: 'expression', english: 'please speak slowly', grammar: 'phrase' },
    { latinised: 'sà nǎam bin', thai: 'สนามบิน', type: 'word', english: 'airport', grammar: 'noun' },
    { latinised: 'sà thǎa nii rót fai', thai: 'สถานีรถไฟ', type: 'expression', english: 'train station', grammar: 'noun' },
    { latinised: 'sà thǎa nii khǒn sòng', thai: 'สถานีขนส่ง', type: 'expression', english: 'bus terminal', grammar: 'noun' },
    { latinised: 'boo khǒo sǒo', thai: 'บขส.', type: 'word', english: 'bus terminal (abbr.)', grammar: 'noun' },
    { latinised: 'sà thǎa nii dtam rùat', thai: 'สถานีตำรวจ', type: 'expression', english: 'police station', grammar: 'noun' },
    { latinised: 'thá naa khaan', thai: 'ธนาคาร', type: 'word', english: 'bank', grammar: 'noun' },
    { latinised: 'phák', thai: 'พัก', type: 'word', english: 'to rest / to stay', grammar: 'verb' },
    { latinised: 'thà nǒn', thai: 'ถนน', type: 'word', english: 'road / street', grammar: 'noun' },
    { latinised: 'grung thêep', thai: 'กรุงเทพฯ', type: 'word', english: 'Bangkok', grammar: 'noun' },
    { latinised: 'jing rǔe', thai: 'จริงเหรอ', type: 'expression', english: 'really?', grammar: 'phrase' },
    { latinised: 'jing jing', thai: 'จริงจริง', type: 'expression', english: 'truly / for real', grammar: 'adverb' },
    { latinised: 'bpai nǎi', thai: 'ไปไหน', type: 'expression', english: 'where are you going?', grammar: 'phrase' },
    { latinised: 'bpai nǎi maa', thai: 'ไปไหนมา', type: 'expression', english: 'where have you been?', grammar: 'phrase' },
    { latinised: 'thîaw hâi sà nùk ná', thai: 'เที่ยวให้สนุกนะ', type: 'expression', english: 'have a fun trip!', grammar: 'phrase' },
    { latinised: 'bâan', thai: 'บ้าน', type: 'word', english: 'house / home', grammar: 'noun' },
    { latinised: 'rót', thai: 'รถ', type: 'word', english: 'car / vehicle', grammar: 'noun' },
    { latinised: 'súe', thai: 'ซื้อ', type: 'word', english: 'to buy', grammar: 'verb' },
    { latinised: 'súe à rai', thai: 'ซื้ออะไร', type: 'expression', english: 'buy what?', grammar: 'phrase' },
    { latinised: 'lên', thai: 'เล่น', type: 'word', english: 'to play', grammar: 'verb' },
    { latinised: 'khun tham à rai yùu', thai: 'คุณทำอะไรอยู่', type: 'expression', english: 'what are you doing?', grammar: 'phrase' },
    { latinised: 'mâi rúu', thai: 'ไม่รู้', type: 'expression', english: "don't know", grammar: 'phrase' },
    { latinised: 'khun rúu jàk kháo mǎi', thai: 'คุณรู้จักเขาไหม', type: 'expression', english: 'do you know him/her?', grammar: 'phrase' },
    { latinised: 'bpai dooen lên', thai: 'ไปเดินเล่น', type: 'expression', english: 'go for a walk', grammar: 'phrase' },
    { latinised: 'gin khâao dûai gan', thai: 'กินข้าวด้วยกัน', type: 'expression', english: 'eat together', grammar: 'phrase' },
    { latinised: 'phaeng', thai: 'แพง', type: 'word', english: 'expensive', grammar: 'adjective' },
    { latinised: 'mâi phaeng', thai: 'ไม่แพง', type: 'expression', english: 'not expensive', grammar: 'phrase' },
    { latinised: 'ao', thai: 'เอา', type: 'word', english: 'to want / to take', grammar: 'verb' },
    { latinised: 'mâi ao', thai: 'ไม่เอา', type: 'expression', english: "don't want", grammar: 'phrase' },
    { latinised: 'dâi mǎi', thai: 'ได้ไหม', type: 'expression', english: 'can you? / is it ok?', grammar: 'phrase' },
    { latinised: 'dâi', thai: 'ได้', type: 'word', english: 'can / to get', grammar: 'verb' },
    { latinised: 'mâi dâi', thai: 'ไม่ได้', type: 'expression', english: 'cannot', grammar: 'phrase' },
    { latinised: 'bàat', thai: 'บาท', type: 'word', english: 'baht (currency)', grammar: 'noun' },
    { latinised: 'sûea', thai: 'เสื้อ', type: 'word', english: 'shirt / top', grammar: 'noun' },
    { latinised: 'gaang geng', thai: 'กางเกง', type: 'word', english: 'trousers / pants', grammar: 'noun' },
    { latinised: 'grà bproong', thai: 'กระโปรง', type: 'word', english: 'skirt', grammar: 'noun' },
    { latinised: 'roong tháo', thai: 'รองเท้า', type: 'word', english: 'shoes', grammar: 'noun' },
    { latinised: 'thǔng tháo', thai: 'ถุงเท้า', type: 'word', english: 'socks', grammar: 'noun' },
    { latinised: 'khèm khàt', thai: 'เข็มขัด', type: 'word', english: 'belt', grammar: 'noun' },
    { latinised: 'wâen', thai: 'แว่น', type: 'word', english: 'glasses', grammar: 'noun' },
    { latinised: 'naa lí kaa', thai: 'นาฬิกา', type: 'word', english: 'watch / clock', grammar: 'noun' },
    { latinised: 'lót', thai: 'ลด', type: 'word', english: 'to reduce / discount', grammar: 'verb' },
    { latinised: 'thâo rài', thai: 'เท่าไร', type: 'expression', english: 'how much?', grammar: 'phrase' },
    { latinised: 'an nîi thâo rài', thai: 'อันนี้เท่าไร', type: 'expression', english: 'how much is this?', grammar: 'phrase' },
    { latinised: 'lót nòi dâi mǎi', thai: 'ลดหน่อยได้ไหม', type: 'expression', english: 'can you lower the price?', grammar: 'phrase' },
    { latinised: 'ao mǎi', thai: 'เอาไหม', type: 'expression', english: 'do you want it?', grammar: 'phrase' },
    { latinised: 'thoo rá sàp', thai: 'โทรศัพท์', type: 'word', english: 'telephone', grammar: 'noun' },
    { latinised: 'khun aa yú thâo rài', thai: 'คุณอายุเท่าไร', type: 'expression', english: 'how old are you?', grammar: 'phrase' },
    { latinised: 'nám dtòk', thai: 'น้ำตก', type: 'word', english: 'waterfall', grammar: 'noun' },
    { latinised: 'dta làat', thai: 'ตลาด', type: 'word', english: 'market', grammar: 'noun' },
    { latinised: 'wát', thai: 'วัด', type: 'word', english: 'temple', grammar: 'noun' },
    { latinised: 'mâe nám', thai: 'แม่น้ำ', type: 'word', english: 'river', grammar: 'noun' },
    { latinised: 'aa hǎan', thai: 'อาหาร', type: 'word', english: 'food', grammar: 'noun' },
    { latinised: 'aa hǎan thai', thai: 'อาหารไทย', type: 'expression', english: 'Thai food', grammar: 'noun' },
    { latinised: 'aa hǎan fà ràng', thai: 'อาหารฝรั่ง', type: 'expression', english: 'Western food', grammar: 'noun' },
    { latinised: 'khài', thai: 'ไข่', type: 'word', english: 'egg', grammar: 'noun' },
    { latinised: 'khài jiiaw', thai: 'ไข่เจียว', type: 'expression', english: 'omelette', grammar: 'noun' },
    { latinised: 'khài daao', thai: 'ไข่ดาว', type: 'expression', english: 'fried egg', grammar: 'noun' },
    { latinised: 'bpuu', thai: 'ปู', type: 'word', english: 'crab', grammar: 'noun' },
    { latinised: 'bplaa mùek', thai: 'ปลาหมึก', type: 'word', english: 'squid', grammar: 'noun' },
    { latinised: 'dtâo hûu', thai: 'เต้าหู้', type: 'word', english: 'tofu', grammar: 'noun' },
    { latinised: 'phàk', thai: 'ผัก', type: 'word', english: 'vegetables', grammar: 'noun' },
    { latinised: 'phàt bprîaw wǎan', thai: 'ผัดเปรี้ยวหวาน', type: 'expression', english: 'sweet and sour stir-fry', grammar: 'noun' },
    { latinised: 'gaeng phèt', thai: 'แกงเผ็ด', type: 'expression', english: 'red curry', grammar: 'noun' },
    { latinised: 'sôm dtam', thai: 'ส้มตำ', type: 'expression', english: 'papaya salad', grammar: 'noun' },
    { latinised: 'lûuk chín', thai: 'ลูกชิ้น', type: 'expression', english: 'meatball', grammar: 'noun' },
    { latinised: 'bà mìi', thai: 'บะหมี่', type: 'word', english: 'egg noodles', grammar: 'noun' },
    { latinised: 'sên yài', thai: 'เส้นใหญ่', type: 'expression', english: 'wide rice noodles', grammar: 'noun' },
    { latinised: 'sên mìi', thai: 'เส้นหมี่', type: 'expression', english: 'thin rice noodles', grammar: 'noun' },
    { latinised: 'khǒo', thai: 'ขอ', type: 'word', english: 'to request / may I', grammar: 'verb' },
    { latinised: 'nòi', thai: 'หน่อย', type: 'word', english: 'a little', grammar: 'adverb' },
    { latinised: 'gǔai dtǐaw', thai: 'ก๋วยเตี๋ยว', type: 'word', english: 'noodle soup', grammar: 'noun' },
    { latinised: 'dtôm yam', thai: 'ต้มยำ', type: 'expression', english: 'spicy sour soup', grammar: 'noun' },
    { latinised: 'khâao', thai: 'ข้าว', type: 'word', english: 'rice', grammar: 'noun' },
    { latinised: 'khâao phàt', thai: 'ข้าวผัด', type: 'expression', english: 'fried rice', grammar: 'noun' },
    { latinised: 'khâao nǐaw', thai: 'ข้าวเหนียว', type: 'expression', english: 'sticky rice', grammar: 'noun' },
    { latinised: 'khâao sǔay', thai: 'ข้าวสวย', type: 'expression', english: 'steamed rice', grammar: 'noun' },
    { latinised: 'khâao dtôm', thai: 'ข้าวต้ม', type: 'expression', english: 'rice porridge', grammar: 'noun' },
    { latinised: 'phàt thai', thai: 'ผัดไทย', type: 'expression', english: 'pad thai', grammar: 'noun' },
    { latinised: 'phàt gà phrao', thai: 'ผัดกะเพรา', type: 'expression', english: 'holy basil stir-fry', grammar: 'noun' },
    { latinised: 'phàt phàk ruam', thai: 'ผัดผักรวม', type: 'expression', english: 'mixed vegetable stir-fry', grammar: 'noun' },
    { latinised: 'dtôm khàa gài', thai: 'ต้มข่าไก่', type: 'expression', english: 'chicken galangal soup', grammar: 'noun' },
    { latinised: 'dtôm yam gûng', thai: 'ต้มยำกุ้ง', type: 'expression', english: 'spicy shrimp soup', grammar: 'noun' },
    { latinised: 'gaeng mát sà man', thai: 'แกงมัสมั่น', type: 'expression', english: 'massaman curry', grammar: 'noun' },
    { latinised: 'gaeng khǐaw wǎan', thai: 'แกงเขียวหวาน', type: 'expression', english: 'green curry', grammar: 'noun' },
    { latinised: 'bplaa thôot', thai: 'ปลาทอด', type: 'expression', english: 'fried fish', grammar: 'noun' },
    { latinised: 'gài yâang', thai: 'ไก่ย่าง', type: 'expression', english: 'grilled chicken', grammar: 'noun' },
    { latinised: 'jaan', thai: 'จาน', type: 'word', english: 'plate', grammar: 'noun' },
    { latinised: 'gâew', thai: 'แก้ว', type: 'word', english: 'glass', grammar: 'noun' },
    { latinised: 'khùat', thai: 'ขวด', type: 'word', english: 'bottle', grammar: 'noun' },
    { latinised: 'chaam', thai: 'ชาม', type: 'word', english: 'bowl', grammar: 'noun' },
    { latinised: 'bia', thai: 'เบียร์', type: 'word', english: 'beer', grammar: 'noun' },
    { latinised: 'nám', thai: 'น้ำ', type: 'word', english: 'water', grammar: 'noun' },
];
