export type VocabularyCategory = 'basics' | 'places' | 'food' | 'numbers' | 'shopping' | 'daily-life';

export const VOCABULARY_CATEGORIES: { id: VocabularyCategory; label: string }[] = [
    { id: 'basics', label: 'Basics' },
    { id: 'places', label: 'Places' },
    { id: 'food', label: 'Food' },
    { id: 'numbers', label: 'Numbers' },
    { id: 'shopping', label: 'Shopping' },
    { id: 'daily-life', label: 'Daily Life' },
];

export interface VocabItem {
    latinised: string;
    thai: string;
    type: 'word' | 'expression';
    english: string;
    grammar: string;
    category: VocabularyCategory;
}

export const VOCABULARY: VocabItem[] = [
    { latinised: 'pǒm', thai: 'ผม', type: 'word', english: 'I (male)', grammar: 'pronoun', category: 'basics' },
    { latinised: 'dì chǎn', thai: 'ดิฉัน', type: 'word', english: 'I (female)', grammar: 'pronoun', category: 'basics' },
    { latinised: 'khun', thai: 'คุณ', type: 'word', english: 'you (formal)', grammar: 'pronoun', category: 'basics' },
    { latinised: 'kháo', thai: 'เขา', type: 'word', english: 'he / she / they', grammar: 'pronoun', category: 'basics' },
    { latinised: 'rao', thai: 'เรา', type: 'word', english: 'we / us', grammar: 'pronoun', category: 'basics' },
    { latinised: 'sà wàt dii', thai: 'สวัสดี', type: 'word', english: 'hello / good day', grammar: 'interjection', category: 'basics' },
    { latinised: 'chûue', thai: 'ชื่อ', type: 'word', english: 'name', grammar: 'noun', category: 'basics' },
    { latinised: 'khâ', thai: 'ค่ะ', type: 'word', english: 'polite particle (female / statement)', grammar: 'particle', category: 'basics' },
    { latinised: 'ká', thai: 'คะ', type: 'word', english: 'polite particle (female / question)', grammar: 'particle', category: 'basics' },
    { latinised: 'kráp', thai: 'ครับ', type: 'word', english: 'polite particle (male)', grammar: 'particle', category: 'basics' },
    { latinised: 'sà baai', thai: 'สบาย', type: 'word', english: 'comfortable', grammar: 'adjective', category: 'basics' },
    { latinised: 'dii', thai: 'ดี', type: 'word', english: 'good / well', grammar: 'adjective', category: 'basics' },
    { latinised: 'maa', thai: 'มา', type: 'word', english: 'to come', grammar: 'verb', category: 'basics' },
    { latinised: 'jàak', thai: 'จาก', type: 'word', english: 'from', grammar: 'preposition', category: 'basics' },
    { latinised: 'phûut', thai: 'พูด', type: 'word', english: 'to speak', grammar: 'verb', category: 'basics' },
    { latinised: 'yin dii', thai: 'ยินดี', type: 'word', english: 'pleased / glad', grammar: 'adjective', category: 'basics' },
    { latinised: 'phrûng nîi', thai: 'พรุ่งนี้', type: 'word', english: 'tomorrow', grammar: 'noun', category: 'daily-life' },
    { latinised: 'phûu yǐng', thai: 'ผู้หญิง', type: 'word', english: 'woman', grammar: 'noun', category: 'daily-life' },
    { latinised: 'phûu chaai', thai: 'ผู้ชาย', type: 'word', english: 'man', grammar: 'noun', category: 'daily-life' },
    { latinised: 'rón', thai: 'ร้อน', type: 'word', english: 'hot', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'sà nùk', thai: 'สนุก', type: 'word', english: 'fun', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'nùeai', thai: 'เหนื่อย', type: 'word', english: 'tired', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'hǐu', thai: 'หิว', type: 'word', english: 'hungry', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'sǔai', thai: 'สวย', type: 'word', english: 'beautiful', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'lòo', thai: 'หล่อ', type: 'word', english: 'handsome', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'mâak', thai: 'มาก', type: 'word', english: 'very / a lot', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'bprà thêet', thai: 'ประเทศ', type: 'word', english: 'country', grammar: 'noun', category: 'places' },
    { latinised: 'mueang', thai: 'เมือง', type: 'word', english: 'city / town', grammar: 'noun', category: 'places' },
    { latinised: 'jang wàt', thai: 'จังหวัด', type: 'word', english: 'province', grammar: 'noun', category: 'places' },
    { latinised: 'rát', thai: 'รัฐ', type: 'word', english: 'state', grammar: 'noun', category: 'places' },
    { latinised: 'nǎao', thai: 'หนาว', type: 'word', english: 'cold (feeling)', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'yen', thai: 'เย็น', type: 'word', english: 'cold / cool', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'à ròi', thai: 'อร่อย', type: 'word', english: 'delicious', grammar: 'adjective', category: 'food' },
    { latinised: 'phèt', thai: 'เผ็ด', type: 'word', english: 'spicy', grammar: 'adjective', category: 'food' },
    { latinised: 'yùu', thai: 'อยู่', type: 'word', english: 'to live / to stay', grammar: 'verb', category: 'places' },
    { latinised: 'thîi', thai: 'ที่', type: 'word', english: 'at / place', grammar: 'preposition', category: 'places' },
    { latinised: 'hông', thai: 'ห้อง', type: 'word', english: 'room', grammar: 'noun', category: 'places' },
    { latinised: 'ráan', thai: 'ร้าน', type: 'word', english: 'shop', grammar: 'noun', category: 'places' },
    { latinised: 'aa hǎan', thai: 'อาหาร', type: 'word', english: 'food', grammar: 'noun', category: 'food' },
    { latinised: 'roong', thai: 'โรง', type: 'word', english: 'big building', grammar: 'noun', category: 'places' },
    { latinised: 'thá leh', thai: 'ทะเล', type: 'word', english: 'sea', grammar: 'noun', category: 'places' },
    { latinised: 'phuu kháo', thai: 'ภูเขา', type: 'word', english: 'mountain', grammar: 'noun', category: 'places' },
    { latinised: 'wát', thai: 'วัด', type: 'word', english: 'temple', grammar: 'noun', category: 'places' },
    { latinised: 'dta làat', thai: 'ตลาด', type: 'word', english: 'market', grammar: 'noun', category: 'places' },
    { latinised: 'bpàa', thai: 'ป่า', type: 'word', english: 'forest', grammar: 'noun', category: 'places' },
    { latinised: 'thá naa khaan', thai: 'ธนาคาร', type: 'word', english: 'bank', grammar: 'noun', category: 'places' },
    { latinised: 'phák', thai: 'พัก', type: 'word', english: 'to stay / to rest', grammar: 'verb', category: 'places' },
    { latinised: 'thà nǒn', thai: 'ถนน', type: 'word', english: 'road / street', grammar: 'noun', category: 'places' },
    { latinised: 'grung thêep', thai: 'กรุงเทพฯ', type: 'word', english: 'Bangkok', grammar: 'noun', category: 'places' },
    { latinised: 'glâi', thai: 'ใกล้', type: 'word', english: 'near', grammar: 'adjective', category: 'places' },
    { latinised: 'bâan', thai: 'บ้าน', type: 'word', english: 'house / home', grammar: 'noun', category: 'places' },
    { latinised: 'mâe', thai: 'แม่', type: 'word', english: 'mother', grammar: 'noun', category: 'daily-life' },
    { latinised: 'phûean', thai: 'เพื่อน', type: 'word', english: 'friend', grammar: 'noun', category: 'daily-life' },
    { latinised: 'faen', thai: 'แฟน', type: 'word', english: 'boyfriend / girlfriend / spouse', grammar: 'noun', category: 'daily-life' },
    { latinised: 'khǒng', thai: 'ของ', type: 'word', english: 'of / belong to / things', grammar: 'preposition', category: 'daily-life' },
    { latinised: 'bpai', thai: 'ไป', type: 'word', english: 'to go', grammar: 'verb', category: 'daily-life' },
    { latinised: 'chôop', thai: 'ชอบ', type: 'word', english: 'to like', grammar: 'verb', category: 'daily-life' },
    { latinised: 'láew', thai: 'แล้ว', type: 'word', english: 'and / then', grammar: 'conjunction', category: 'daily-life' },
    { latinised: 'gin', thai: 'กิน', type: 'word', english: 'to eat', grammar: 'verb', category: 'food' },
    { latinised: 'tham', thai: 'ทำ', type: 'word', english: 'to do / to make', grammar: 'verb', category: 'daily-life' },
    { latinised: 'duu', thai: 'ดู', type: 'word', english: 'to watch / to see', grammar: 'verb', category: 'daily-life' },
    { latinised: 'súe', thai: 'ซื้อ', type: 'word', english: 'to buy', grammar: 'verb', category: 'shopping' },
    { latinised: 'lên', thai: 'เล่น', type: 'word', english: 'to play', grammar: 'verb', category: 'daily-life' },
    { latinised: 'fang', thai: 'ฟัง', type: 'word', english: 'to listen', grammar: 'verb', category: 'daily-life' },
    { latinised: 'àan', thai: 'อ่าน', type: 'word', english: 'to read', grammar: 'verb', category: 'daily-life' },
    { latinised: 'khǐan', thai: 'เขียน', type: 'word', english: 'to write', grammar: 'verb', category: 'daily-life' },
    { latinised: 'yàak', thai: 'อยาก', type: 'word', english: 'to want', grammar: 'verb', category: 'daily-life' },
    { latinised: 'khâao', thai: 'ข้าว', type: 'word', english: 'rice', grammar: 'noun', category: 'food' },
    { latinised: 'nám', thai: 'น้ำ', type: 'word', english: 'water', grammar: 'noun', category: 'food' },
    { latinised: 'ngaan', thai: 'งาน', type: 'word', english: 'job / work', grammar: 'noun', category: 'daily-life' },
    { latinised: 'nǎng', thai: 'หนัง', type: 'word', english: 'movie / film', grammar: 'noun', category: 'daily-life' },
    { latinised: 'rót', thai: 'รถ', type: 'word', english: 'car / vehicle', grammar: 'noun', category: 'daily-life' },
    { latinised: 'bpia noo', thai: 'เปียโน', type: 'word', english: 'piano', grammar: 'noun', category: 'daily-life' },
    { latinised: 'bàet min dtân', thai: 'แบดมินตัน', type: 'word', english: 'badminton', grammar: 'noun', category: 'daily-life' },
    { latinised: 'gii laa', thai: 'กีฬา', type: 'word', english: 'sport', grammar: 'noun', category: 'daily-life' },
    { latinised: 'phaa sǎa', thai: 'ภาษา', type: 'word', english: 'language', grammar: 'noun', category: 'daily-life' },
    { latinised: 'thai', thai: 'ไทย', type: 'word', english: 'Thai', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'ang grìt', thai: 'อังกฤษ', type: 'word', english: 'English', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'yîi bpùn', thai: 'ญี่ปุ่น', type: 'word', english: 'Japanese / Japan', grammar: 'noun', category: 'daily-life' },
    { latinised: 'dâi', thai: 'ได้', type: 'word', english: 'can / to get', grammar: 'verb', category: 'daily-life' },
    { latinised: 'nawn', thai: 'นอน', type: 'word', english: 'to sleep', grammar: 'verb', category: 'daily-life' },
    { latinised: 'dooen', thai: 'เดิน', type: 'word', english: 'to walk', grammar: 'verb', category: 'daily-life' },
    { latinised: 'rian', thai: 'เรียน', type: 'word', english: 'to study', grammar: 'verb', category: 'daily-life' },
    { latinised: 'dtên', thai: 'เต้น', type: 'word', english: 'to dance', grammar: 'verb', category: 'daily-life' },
    { latinised: 'rúu', thai: 'รู้', type: 'word', english: 'to know', grammar: 'verb', category: 'daily-life' },
    { latinised: 'gàp', thai: 'กับ', type: 'word', english: 'with / and', grammar: 'preposition', category: 'daily-life' },
    { latinised: 'gèng', thai: 'เก่ง', type: 'word', english: 'good at', grammar: 'adjective', category: 'daily-life' },
    { latinised: 'dûai', thai: 'ด้วย', type: 'word', english: 'too / also', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'bpòet', thai: 'เปิด', type: 'word', english: 'to open / turn on', grammar: 'verb', category: 'daily-life' },
    { latinised: 'bpìt', thai: 'ปิด', type: 'word', english: 'to close / turn off', grammar: 'verb', category: 'daily-life' },
    { latinised: 'luuem', thai: 'ลืม', type: 'word', english: 'to forget', grammar: 'verb', category: 'daily-life' },
    { latinised: 'à rai', thai: 'อะไร', type: 'word', english: 'what', grammar: 'pronoun', category: 'daily-life' },
    { latinised: 'mâi', thai: 'ไม่', type: 'word', english: 'not / no', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'sǔun', thai: 'ศูนย์', type: 'word', english: 'zero', grammar: 'number', category: 'numbers' },
    { latinised: 'nùeng', thai: 'หนึ่ง', type: 'word', english: 'one', grammar: 'number', category: 'numbers' },
    { latinised: 'sǎawng', thai: 'สอง', type: 'word', english: 'two', grammar: 'number', category: 'numbers' },
    { latinised: 'sǎam', thai: 'สาม', type: 'word', english: 'three', grammar: 'number', category: 'numbers' },
    { latinised: 'sìi', thai: 'สี่', type: 'word', english: 'four', grammar: 'number', category: 'numbers' },
    { latinised: 'hâa', thai: 'ห้า', type: 'word', english: 'five', grammar: 'number', category: 'numbers' },
    { latinised: 'hòk', thai: 'หก', type: 'word', english: 'six', grammar: 'number', category: 'numbers' },
    { latinised: 'jèt', thai: 'เจ็ด', type: 'word', english: 'seven', grammar: 'number', category: 'numbers' },
    { latinised: 'bpàet', thai: 'แปด', type: 'word', english: 'eight', grammar: 'number', category: 'numbers' },
    { latinised: 'gâo', thai: 'เก้า', type: 'word', english: 'nine', grammar: 'number', category: 'numbers' },
    { latinised: 'sìp', thai: 'สิบ', type: 'word', english: 'ten', grammar: 'number', category: 'numbers' },
    { latinised: 'rói', thai: 'ร้อย', type: 'word', english: 'hundred', grammar: 'number', category: 'numbers' },
    { latinised: 'phan', thai: 'พัน', type: 'word', english: 'thousand', grammar: 'number', category: 'numbers' },
    { latinised: 'mùuen', thai: 'หมื่น', type: 'word', english: 'ten thousand', grammar: 'number', category: 'numbers' },
    { latinised: 'sǎen', thai: 'แสน', type: 'word', english: 'hundred thousand', grammar: 'number', category: 'numbers' },
    { latinised: 'láan', thai: 'ล้าน', type: 'word', english: 'million', grammar: 'number', category: 'numbers' },
    { latinised: 'ngoen', thai: 'เงิน', type: 'word', english: 'money', grammar: 'noun', category: 'shopping' },
    { latinised: 'bàat', thai: 'บาท', type: 'word', english: 'baht (currency)', grammar: 'noun', category: 'shopping' },
    { latinised: 'dawn laa', thai: 'ดอลลาร์', type: 'word', english: 'dollar', grammar: 'noun', category: 'shopping' },
    { latinised: 'khǎai', thai: 'ขาย', type: 'word', english: 'to sell', grammar: 'verb', category: 'shopping' },
    { latinised: 'thùuk', thai: 'ถูก', type: 'word', english: 'cheap', grammar: 'adjective', category: 'shopping' },
    { latinised: 'ao', thai: 'เอา', type: 'word', english: 'to want / to take', grammar: 'verb', category: 'shopping' },
    { latinised: 'thoo rá sàp', thai: 'โทรศัพท์', type: 'word', english: 'telephone', grammar: 'noun', category: 'shopping' },
    { latinised: 'boe', thai: 'เบอร์', type: 'word', english: 'number (phone)', grammar: 'noun', category: 'shopping' },
    { latinised: 'sûea', thai: 'เสื้อ', type: 'word', english: 'shirt / blouse', grammar: 'noun', category: 'shopping' },
    { latinised: 'khèm khàt', thai: 'เข็มขัด', type: 'word', english: 'belt', grammar: 'noun', category: 'shopping' },
    { latinised: 'gaang geng', thai: 'กางเกง', type: 'word', english: 'trousers / pants', grammar: 'noun', category: 'shopping' },
    { latinised: 'grà bproong', thai: 'กระโปรง', type: 'word', english: 'skirt', grammar: 'noun', category: 'shopping' },
    { latinised: 'roong tháo', thai: 'รองเท้า', type: 'word', english: 'shoes', grammar: 'noun', category: 'shopping' },
    { latinised: 'thǔng tháo', thai: 'ถุงเท้า', type: 'word', english: 'socks', grammar: 'noun', category: 'shopping' },
    { latinised: 'mùak', thai: 'หมวก', type: 'word', english: 'hat', grammar: 'noun', category: 'shopping' },
    { latinised: 'naa lí kaa', thai: 'นาฬิกา', type: 'word', english: 'watch / clock', grammar: 'noun', category: 'shopping' },
    { latinised: 'wâen dtaa', thai: 'แว่นตา', type: 'word', english: 'glasses', grammar: 'noun', category: 'shopping' },
    { latinised: 'wǎen', thai: 'แหวน', type: 'word', english: 'ring (jewelry)', grammar: 'noun', category: 'shopping' },
    { latinised: 'gam lai', thai: 'กำไล', type: 'word', english: 'bracelet', grammar: 'noun', category: 'shopping' },
    { latinised: 'lót', thai: 'ลด', type: 'word', english: 'to reduce / discount', grammar: 'verb', category: 'shopping' },
    { latinised: 'nòi', thai: 'หน่อย', type: 'word', english: 'a little / please', grammar: 'adverb', category: 'shopping' },
    { latinised: 'aa yú', thai: 'อายุ', type: 'word', english: 'age', grammar: 'noun', category: 'shopping' },
    { latinised: 'bpii', thai: 'ปี', type: 'word', english: 'year', grammar: 'noun', category: 'shopping' },
    { latinised: 'phaeng', thai: 'แพง', type: 'word', english: 'expensive', grammar: 'adjective', category: 'shopping' },
    { latinised: 'gìi', thai: 'กี่', type: 'word', english: 'how many?', grammar: 'pronoun', category: 'shopping' },
    { latinised: 'phàt', thai: 'ผัด', type: 'word', english: 'to stir fry', grammar: 'verb', category: 'food' },
    { latinised: 'thôot', thai: 'ทอด', type: 'word', english: 'to deep fry', grammar: 'verb', category: 'food' },
    { latinised: 'dtôm', thai: 'ต้ม', type: 'word', english: 'to boil', grammar: 'verb', category: 'food' },
    { latinised: 'gaeng', thai: 'แกง', type: 'word', english: 'curry', grammar: 'noun', category: 'food' },
    { latinised: 'mǔu', thai: 'หมู', type: 'word', english: 'pork', grammar: 'noun', category: 'food' },
    { latinised: 'gài', thai: 'ไก่', type: 'word', english: 'chicken', grammar: 'noun', category: 'food' },
    { latinised: 'núea', thai: 'เนื้อ', type: 'word', english: 'beef', grammar: 'noun', category: 'food' },
    { latinised: 'gûng', thai: 'กุ้ง', type: 'word', english: 'shrimp', grammar: 'noun', category: 'food' },
    { latinised: 'bplaa', thai: 'ปลา', type: 'word', english: 'fish', grammar: 'noun', category: 'food' },
    { latinised: 'khǒo', thai: 'ขอ', type: 'word', english: 'to request / may I', grammar: 'verb', category: 'food' },
    { latinised: 'khài', thai: 'ไข่', type: 'word', english: 'egg', grammar: 'noun', category: 'food' },
    { latinised: 'gǔai dtǐaw', thai: 'ก๋วยเตี๋ยว', type: 'word', english: 'noodle soup', grammar: 'noun', category: 'food' },
    { latinised: 'bpuu', thai: 'ปู', type: 'word', english: 'crab', grammar: 'noun', category: 'food' },
    { latinised: 'bplaa mùek', thai: 'ปลาหมึก', type: 'word', english: 'squid', grammar: 'noun', category: 'food' },
    { latinised: 'dtâo hûu', thai: 'เต้าหู้', type: 'word', english: 'tofu', grammar: 'noun', category: 'food' },
    { latinised: 'phàk', thai: 'ผัก', type: 'word', english: 'vegetables', grammar: 'noun', category: 'food' },
    { latinised: 'bà mìi', thai: 'บะหมี่', type: 'word', english: 'egg noodles', grammar: 'noun', category: 'food' },
    { latinised: 'jaan', thai: 'จาน', type: 'word', english: 'plate', grammar: 'noun', category: 'food' },
    { latinised: 'gâew', thai: 'แก้ว', type: 'word', english: 'glass (drinking)', grammar: 'noun', category: 'food' },
    { latinised: 'khùat', thai: 'ขวด', type: 'word', english: 'bottle', grammar: 'noun', category: 'food' },
    { latinised: 'chaam', thai: 'ชาม', type: 'word', english: 'bowl', grammar: 'noun', category: 'food' },
    { latinised: 'bia', thai: 'เบียร์', type: 'word', english: 'beer', grammar: 'noun', category: 'food' },
    // ── basics (restored) ──
    { latinised: 'chûue lên', thai: 'ชื่อเล่น', type: 'expression', english: 'nickname', grammar: 'noun', category: 'basics' },
    { latinised: 'chûue jing', thai: 'ชื่อจริง', type: 'expression', english: 'first name', grammar: 'noun', category: 'basics' },
    { latinised: 'naam sà gun', thai: 'นามสกุล', type: 'expression', english: 'surname', grammar: 'noun', category: 'basics' },
    { latinised: 'sà baai dii', thai: 'สบายดี', type: 'expression', english: 'fine', grammar: 'phrase', category: 'basics' },
    { latinised: 'sà baai dii mǎi', thai: 'สบายดีไหม', type: 'expression', english: 'how are you?', grammar: 'phrase', category: 'basics' },
    { latinised: 'mâi sà baai', thai: 'ไม่สบาย', type: 'expression', english: 'not well / sick', grammar: 'phrase', category: 'basics' },
    { latinised: 'phûut lên', thai: 'พูดเล่น', type: 'expression', english: 'kidding / joking', grammar: 'phrase', category: 'basics' },
    { latinised: 'rúu jàk', thai: 'รู้จัก', type: 'expression', english: 'to know (someone)', grammar: 'verb', category: 'basics' },
    { latinised: 'khǒo thôot', thai: 'ขอโทษ', type: 'expression', english: 'excuse me / sorry', grammar: 'phrase', category: 'basics' },
    { latinised: 'khòop khun', thai: 'ขอบคุณ', type: 'expression', english: 'thank you', grammar: 'phrase', category: 'basics' },
    { latinised: 'mâi bpen rai', thai: 'ไม่เป็นไร', type: 'expression', english: 'never mind / you\'re welcome', grammar: 'phrase', category: 'basics' },
    { latinised: 'láew khun là', thai: 'แล้วคุณล่ะ', type: 'expression', english: 'how about you?', grammar: 'phrase', category: 'basics' },
    { latinised: 'nîi à rai', thai: 'นี่อะไร', type: 'expression', english: 'what is it?', grammar: 'phrase', category: 'basics' },
    { latinised: 'à rai ná', thai: 'อะไรนะ', type: 'expression', english: 'what did you say?', grammar: 'phrase', category: 'basics' },
    { latinised: 'yin dii thîi dâi rúu jàk', thai: 'ยินดีที่ได้รู้จัก', type: 'expression', english: 'pleased to meet you', grammar: 'phrase', category: 'basics' },
    { latinised: 'joe gan', thai: 'เจอกัน', type: 'expression', english: 'see you', grammar: 'phrase', category: 'basics' },
    { latinised: 'phóp gan mài', thai: 'พบกันใหม่', type: 'expression', english: 'see you later', grammar: 'phrase', category: 'basics' },
    { latinised: 'phóp gan phrûng nîi', thai: 'พบกันพรุ่งนี้', type: 'expression', english: 'see you tomorrow', grammar: 'phrase', category: 'basics' },
    { latinised: 'chôok dii', thai: 'โชคดี', type: 'expression', english: 'good luck', grammar: 'phrase', category: 'basics' },
    { latinised: 'yin dii dtôon ráp', thai: 'ยินดีต้อนรับ', type: 'expression', english: 'welcome', grammar: 'phrase', category: 'basics' },
    // ── daily-life (restored) ──
    { latinised: 'nít nòi', thai: 'นิดหน่อย', type: 'expression', english: 'a little bit', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'khâo jai', thai: 'เข้าใจ', type: 'expression', english: 'to understand', grammar: 'verb', category: 'daily-life' },
    { latinised: 'bpai thîaw', thai: 'ไปเที่ยว', type: 'expression', english: 'to take a trip', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'jing rǔe', thai: 'จริงเหรอ', type: 'expression', english: 'really?', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'jing jing', thai: 'จริงจริง', type: 'expression', english: 'truly / for real', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'bpai nǎi', thai: 'ไปไหน', type: 'expression', english: 'where are you going?', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'bpai nǎi maa', thai: 'ไปไหนมา', type: 'expression', english: 'where have you been?', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'thîaw hâi sà nùk ná', thai: 'เที่ยวให้สนุกนะ', type: 'expression', english: 'have a fun trip!', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'gaan bâan', thai: 'การบ้าน', type: 'expression', english: 'homework', grammar: 'noun', category: 'daily-life' },
    { latinised: 'mâi dâi', thai: 'ไม่ได้', type: 'expression', english: 'cannot', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'wâai nám', thai: 'ว่ายน้ำ', type: 'expression', english: 'to swim', grammar: 'verb', category: 'daily-life' },
    { latinised: 'róng phleng', thai: 'ร้องเพลง', type: 'expression', english: 'to sing (a song)', grammar: 'verb', category: 'daily-life' },
    { latinised: 'dûai gan', thai: 'ด้วยกัน', type: 'expression', english: 'together', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'ìik thii', thai: 'อีกที', type: 'expression', english: 'again / one more time', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'cháa cháa', thai: 'ช้าๆ', type: 'expression', english: 'slowly', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'rew rew', thai: 'เร็วๆ', type: 'expression', english: 'quickly / fast', grammar: 'adverb', category: 'daily-life' },
    { latinised: 'dtàe wâa', thai: 'แต่ว่า', type: 'expression', english: 'but', grammar: 'conjunction', category: 'daily-life' },
    { latinised: 'khun tham à rai yùu', thai: 'คุณทำอะไรอยู่', type: 'expression', english: 'what are you doing?', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'mâi rúu', thai: 'ไม่รู้', type: 'expression', english: 'I don\'t know', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'rúu jàk kháo mǎi', thai: 'รู้จักเขาไหม', type: 'expression', english: 'do you know him/her?', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'bpai dooen lên', thai: 'ไปเดินเล่น', type: 'expression', english: 'go for a walk', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'gin khâao dûai gan', thai: 'กินข้าวด้วยกัน', type: 'expression', english: 'let\'s eat together', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'phûut ìik thii', thai: 'พูดอีกที', type: 'expression', english: 'speak again', grammar: 'phrase', category: 'daily-life' },
    { latinised: 'phûut cháa cháa nòi', thai: 'พูดช้าช้าหน่อย', type: 'expression', english: 'speak slowly please', grammar: 'phrase', category: 'daily-life' },
    // ── places (restored) ──
    { latinised: 'maa jàak', thai: 'มาจาก', type: 'expression', english: 'come from', grammar: 'phrase', category: 'places' },
    { latinised: 'hông nám', thai: 'ห้องน้ำ', type: 'expression', english: 'bathroom', grammar: 'noun', category: 'places' },
    { latinised: 'hông rian', thai: 'ห้องเรียน', type: 'expression', english: 'classroom', grammar: 'noun', category: 'places' },
    { latinised: 'ráan gaa fae', thai: 'ร้านกาแฟ', type: 'expression', english: 'coffee shop', grammar: 'noun', category: 'places' },
    { latinised: 'ráan nǎng sǔue', thai: 'ร้านหนังสือ', type: 'expression', english: 'book store', grammar: 'noun', category: 'places' },
    { latinised: 'roong raem', thai: 'โรงแรม', type: 'expression', english: 'hotel', grammar: 'noun', category: 'places' },
    { latinised: 'roong phá yaa baan', thai: 'โรงพยาบาล', type: 'expression', english: 'hospital', grammar: 'noun', category: 'places' },
    { latinised: 'roong rian', thai: 'โรงเรียน', type: 'expression', english: 'school', grammar: 'noun', category: 'places' },
    { latinised: 'bprai sà nii', thai: 'ไปรษณีย์', type: 'expression', english: 'post office', grammar: 'noun', category: 'places' },
    { latinised: 'má hǎa wít thá yaa lái', thai: 'มหาวิทยาลัย', type: 'expression', english: 'university', grammar: 'noun', category: 'places' },
    { latinised: 'nám dtòk', thai: 'น้ำตก', type: 'expression', english: 'waterfall', grammar: 'noun', category: 'places' },
    { latinised: 'mâe nám', thai: 'แม่น้ำ', type: 'expression', english: 'river', grammar: 'noun', category: 'places' },
    { latinised: 'sà nǎam bin', thai: 'สนามบิน', type: 'expression', english: 'airport', grammar: 'noun', category: 'places' },
    { latinised: 'sà thǎa nii rót fai', thai: 'สถานีรถไฟ', type: 'expression', english: 'railway station', grammar: 'noun', category: 'places' },
    { latinised: 'sà thǎa nii khǒn sòng', thai: 'สถานีขนส่ง', type: 'expression', english: 'bus station', grammar: 'noun', category: 'places' },
    { latinised: 'sà thǎa nii dtam rùat', thai: 'สถานีตำรวจ', type: 'expression', english: 'police station', grammar: 'noun', category: 'places' },
    { latinised: 'thîi nǎi', thai: 'ที่ไหน', type: 'expression', english: 'where?', grammar: 'phrase', category: 'places' },
    { latinised: 'thîi nîi', thai: 'ที่นี่', type: 'expression', english: 'here', grammar: 'adverb', category: 'places' },
    { latinised: 'thîi nân', thai: 'ที่นั่น', type: 'expression', english: 'there', grammar: 'adverb', category: 'places' },
    { latinised: 'thîi nôon', thai: 'ที่โน่น', type: 'expression', english: 'over there', grammar: 'adverb', category: 'places' },
    { latinised: 'dtrong khâam', thai: 'ตรงข้าม', type: 'expression', english: 'opposite', grammar: 'adverb', category: 'places' },
    { latinised: 'dtrong bpai', thai: 'ตรงไป', type: 'expression', english: 'go straight', grammar: 'phrase', category: 'places' },
    { latinised: 'líaw sáai', thai: 'เลี้ยวซ้าย', type: 'expression', english: 'turn left', grammar: 'phrase', category: 'places' },
    { latinised: 'líaw khwǎa', thai: 'เลี้ยวขวา', type: 'expression', english: 'turn right', grammar: 'phrase', category: 'places' },
    // ── numbers (restored) ──
    { latinised: 'sìp èt', thai: 'สิบเอ็ด', type: 'expression', english: 'eleven', grammar: 'number', category: 'numbers' },
    { latinised: 'yîi sìp', thai: 'ยี่สิบ', type: 'expression', english: 'twenty', grammar: 'number', category: 'numbers' },
    // ── shopping (restored) ──
    { latinised: 'an nîi', thai: 'อันนี้', type: 'expression', english: 'this one', grammar: 'pronoun', category: 'shopping' },
    { latinised: 'an nán', thai: 'อันนั้น', type: 'expression', english: 'that one', grammar: 'pronoun', category: 'shopping' },
    { latinised: 'an nóon', thai: 'อันโน้น', type: 'expression', english: 'that one (further away)', grammar: 'pronoun', category: 'shopping' },
    { latinised: 'mâi ao', thai: 'ไม่เอา', type: 'expression', english: 'don\'t want', grammar: 'phrase', category: 'shopping' },
    { latinised: 'dâi mǎi', thai: 'ได้ไหม', type: 'expression', english: 'can you? / is it ok?', grammar: 'phrase', category: 'shopping' },
    { latinised: 'dtûm hǔu', thai: 'ตุ้มหู', type: 'expression', english: 'earring', grammar: 'noun', category: 'shopping' },
    { latinised: 'sôi khoo', thai: 'สร้อยคอ', type: 'expression', english: 'necklace', grammar: 'noun', category: 'shopping' },
    { latinised: 'mâi phaeng', thai: 'ไม่แพง', type: 'expression', english: 'not expensive', grammar: 'phrase', category: 'shopping' },
    { latinised: 'thâo rài', thai: 'เท่าไร', type: 'expression', english: 'how much?', grammar: 'phrase', category: 'shopping' },
    { latinised: 'gìi bàat', thai: 'กี่บาท', type: 'expression', english: 'how many baht?', grammar: 'phrase', category: 'shopping' },
    { latinised: 'an nîi thâo rài', thai: 'อันนี้เท่าไร', type: 'expression', english: 'how much is this?', grammar: 'phrase', category: 'shopping' },
    { latinised: 'lót nòi dâi mǎi', thai: 'ลดหน่อยได้ไหม', type: 'expression', english: 'can you lower the price?', grammar: 'phrase', category: 'shopping' },
    { latinised: 'ao mǎi', thai: 'เอาไหม', type: 'expression', english: 'do you want it?', grammar: 'phrase', category: 'shopping' },
    { latinised: 'thoo rá sàp boe à rai', thai: 'โทรศัพท์เบอร์อะไร', type: 'expression', english: 'what is your phone number?', grammar: 'phrase', category: 'shopping' },
    { latinised: 'khun aa yú thâo rài', thai: 'คุณอายุเท่าไร', type: 'expression', english: 'how old are you?', grammar: 'phrase', category: 'shopping' },
    // ── food (restored) ──
    { latinised: 'khâao phàt', thai: 'ข้าวผัด', type: 'expression', english: 'fried rice', grammar: 'noun', category: 'food' },
    { latinised: 'khâao nǐaw', thai: 'ข้าวเหนียว', type: 'expression', english: 'sticky rice', grammar: 'noun', category: 'food' },
    { latinised: 'khâao sǔay', thai: 'ข้าวสวย', type: 'expression', english: 'steamed rice', grammar: 'noun', category: 'food' },
    { latinised: 'khâao dtôm', thai: 'ข้าวต้ม', type: 'expression', english: 'rice porridge', grammar: 'noun', category: 'food' },
    { latinised: 'phàt thai', thai: 'ผัดไทย', type: 'expression', english: 'pad thai', grammar: 'noun', category: 'food' },
    { latinised: 'phàt gà phrao', thai: 'ผัดกะเพรา', type: 'expression', english: 'holy basil stir-fry', grammar: 'noun', category: 'food' },
    { latinised: 'phàt phàk ruam', thai: 'ผัดผักรวม', type: 'expression', english: 'mixed vegetable stir-fry', grammar: 'noun', category: 'food' },
    { latinised: 'dtôm khàa gài', thai: 'ต้มข่าไก่', type: 'expression', english: 'chicken galangal soup', grammar: 'noun', category: 'food' },
    { latinised: 'dtôm yam gûng', thai: 'ต้มยำกุ้ง', type: 'expression', english: 'spicy shrimp soup', grammar: 'noun', category: 'food' },
    { latinised: 'gaeng mát sà man', thai: 'แกงมัสมั่น', type: 'expression', english: 'massaman curry', grammar: 'noun', category: 'food' },
    { latinised: 'gaeng khǐaw wǎan', thai: 'แกงเขียวหวาน', type: 'expression', english: 'green curry', grammar: 'noun', category: 'food' },
    { latinised: 'gaeng phèt', thai: 'แกงเผ็ด', type: 'expression', english: 'red curry', grammar: 'noun', category: 'food' },
    { latinised: 'phàt bprîaw wǎan', thai: 'ผัดเปรี้ยวหวาน', type: 'expression', english: 'sweet and sour stir-fry', grammar: 'noun', category: 'food' },
    { latinised: 'bplaa thôot', thai: 'ปลาทอด', type: 'expression', english: 'fried fish', grammar: 'noun', category: 'food' },
    { latinised: 'gài yâang', thai: 'ไก่ย่าง', type: 'expression', english: 'grilled chicken', grammar: 'noun', category: 'food' },
    { latinised: 'sôm dtam', thai: 'ส้มตำ', type: 'expression', english: 'papaya salad', grammar: 'noun', category: 'food' },
    { latinised: 'khài jiiaw', thai: 'ไข่เจียว', type: 'expression', english: 'omelette', grammar: 'noun', category: 'food' },
    { latinised: 'khài daao', thai: 'ไข่ดาว', type: 'expression', english: 'fried egg', grammar: 'noun', category: 'food' },
    { latinised: 'khâao soi', thai: 'ข้าวซอย', type: 'expression', english: 'khao soi (egg noodle curry)', grammar: 'noun', category: 'food' },
    { latinised: 'dtôm yam', thai: 'ต้มยำ', type: 'expression', english: 'spicy sour soup', grammar: 'noun', category: 'food' },
    { latinised: 'lûuk chín', thai: 'ลูกชิ้น', type: 'expression', english: 'meatball', grammar: 'noun', category: 'food' },
    { latinised: 'sên yài', thai: 'เส้นใหญ่', type: 'expression', english: 'wide rice noodles', grammar: 'noun', category: 'food' },
    { latinised: 'sên mìi', thai: 'เส้นหมี่', type: 'expression', english: 'thin rice noodles', grammar: 'noun', category: 'food' },
];
